export const translations = {
    ru: {
        select_education_area: 'Выберите область образования',
        ru: 'Русский', kk: 'Қазақша', en: 'English',
        ai_translation: 'Перевод ИИ, прошёл автоматическую проверку',
        dataset_passport: 'Паспорт набора данных', model_benchmark: 'Сравнение моделей',
        research_dashboard: 'Данные и качество модели', research_dashboard_desc: 'Dataset Passport, контрольные выборки и метрики моделей', epvo_programs: 'Программ в экспертной базе', normalized_courses: 'Нормализованных дисциплин', expert_links: 'Экспертных связей', independent_test: 'Независимая тестовая выборка', model: 'Модель', examples: 'Примеров',
        feedback_confirmed: 'Подтвердить', feedback_weak: 'Слабая связь', feedback_incorrect: 'Неверная',
        cycle: 'Цикл', cycle_estimate: 'расчёт системы', component: 'Компонент', source: 'Источник', source_rk_mandatory: 'обязательная дисциплина РК', source_ai_confirmed: 'подтверждённая замена ИИ', source_bridge: 'bridge-модуль', source_repository: 'репозиторий дисциплин', remove_on_regeneration: 'Будет убрана при перегенерации', replace_on_generation: 'Заменить/убрать при следующей генерации', goso_protected: 'Обязательная дисциплина ГОСО РК — защищена от удаления и замены', why_selected: 'Почему выбрана?', lo_links: 'Связи с результатами обучения:', effective: 'итог', ai_short: 'ИИ', epvo_short: 'ЕПВО', bridge_short: 'bridge', weak_link: 'слабая связь', prereq_title: 'Пре- и постреквизиты в этом плане', prereq_note: 'Показываются только дисциплины, которые реально есть в текущем варианте плана.', before_course: 'До этой дисциплины:', after_course: 'После неё опираются:', no_prerequisites: 'в плане нет обязательных предшествующих дисциплин', no_postrequisites: 'в текущем плане нет дисциплин, которые явно требуют её как пререквизит', semester_short: 'Сем.', semester_title: 'Семестр', credits_lower: 'кредитов', explanation_score: 'Проценты относятся к связи одной дисциплины с одним LO. ИИ — прогноз модели по текстам. ЕПВО — поддержка этой же связи в экспертных данных ЕПВО. Они не складываются; итог берётся по наиболее надёжному подтверждению.', explanation_read: 'Как читать: “итог” — насколько дисциплина реально закрывает этот LO в плане; “ИИ” — прогноз модели по текстам; “ЕПВО” — похожая экспертная оценка из базы ЕПВО. Это три разных признака одной связи, они не суммируются.', explanation_effective: 'Итог — итоговая сила связи этой дисциплины с этим LO. ИИ — прогноз модели по текстам. ЕПВО — воспроизведённая экспертная оценка из базы. Они не складываются.', coverage_sources: 'Источники покрытия LO', coverage_sources_desc: 'Показывает, какие результаты закрыты реальными дисциплинами, а какие только bridge-модулями.', show_lo_sources: 'Показать LO-источники', total_los: 'Всего LO', real_courses: 'реальные дисциплины', weak: 'слабые', real_course: 'реальная дисциплина', weak_coverage: 'слабое покрытие', bridge_assumption: '75% — служебная оценка проектного bridge, а не экспертная оценка реальной дисциплины ЕПВО.', bridge_in_plan: 'bridge в плане', show_in_plan: 'Показать в плане',
        ai_prediction: 'прогноз ИИ', metrics_refresh: 'Метрики плана требуют обновления', metrics_refresh_desc: 'Этот вариант создан предыдущей версией валидатора. Перестройте вариант, чтобы заново проверить кредиты, нагрузку, пререквизиты и доказательства LO.', rebuild_verify: 'Перестроить и проверить', fix_quality: 'Исправить порядок, нагрузку и кредиты', epvo_courses: 'Дисциплины плана из ЕПВО', typical_courses: 'типовых дисциплин', expert_links_label: 'экспертных связей', full_epvo_analysis: 'Полный анализ ЕПВО', suspicious_courses: 'Сомнительные дисциплины', find_all_replacements: 'Подобрать замены для всех видимых', find_replacements: 'Подобрать 3 замены', reason_wrong_level: 'не соответствует уровню образования', reason_not_core: 'не ядро программы', reason_weak_evidence: 'слабое LO-доказательство', reason_too_early: 'слишком рано', best_link: 'Лучшая связь', confirm_link: 'Подтвердить связь', keep_in_plan: 'Оставить в плане', mark_replacement: 'Отметить на замену', replacing: 'Замена…', confirm_replacement: 'Подтвердить замену', no_equivalent: 'Подходящей равноценной замены пока нет.', professional_los: 'Профессиональные LO', recommended_semester: 'рекомендуемый семестр', system_not_blocking: 'Система не блокирует просмотр, но такие дисциплины нужно заменить или подтвердить экспертом.', searching_replacements: 'Ищем замены…', search_replacements: 'Поиск…', replace_on_regeneration_checked: '✓ Заменить при перегенерации', replacement_preview_done: 'Подбор замен выполнен за {seconds}s.',
        compare_epvo: 'Сравнить с экспертной базой', epvo_reference_courses: 'Дисциплин в выборке CEER', present_in_plan: 'Есть в плане', missing_from_plan: 'Отсутствуют', typical_epvo_courses: 'Типовые дисциплины экспертной базы', source_programs: 'Программ-источников', present: 'Есть', missing: 'Нет',
        select_direction: 'Выберите направление', select_group: 'Выберите группу ОП',
        building_plan: 'Построение плана',
        education_level: 'Уровень образования', regulatory_profile: 'Нормативный профиль', ruleset_version: 'Редакция ruleset', goso_compliance_title: 'Соответствие ГОСО Республики Казахстан', status_label: 'Статус', goso_compliant: 'соответствует', goso_violations: 'есть нарушения', mandatory_credits: 'Обязательные кредиты', automatic_quality_audit: 'Автоматическая проверка качества плана', quality_passed: 'План прошёл проверку связей с РО и последовательности семестров.', quality_needs_corrections: 'План требует исправлений до экспертного утверждения.', semester_load_band: 'Нагрузка за семестр: цель (допустимый диапазон)', structural_prerequisites: 'Структурные пререквизиты', los_without_real_course: 'РО без реальной дисциплины', weak_courses: 'Слабые дисциплины', semester_misplacements: 'Неуместный семестр', best_real_link: 'лучшая реальная связь', recommended: 'рекомендуется', bachelor: 'Бакалавриат', master: 'Магистратура', doctorate: 'Докторантура', education_area: 'Область образования', direction_code: 'Направление подготовки', group_code: 'Группа образовательных программ', program_type: 'Тип программы', standard_program: 'Стандартная', interdisciplinary_program: 'Междисциплинарная', joint_program: 'Совместная', instruction_language: 'Язык обучения',
        curriculum_workspace: 'Рабочее пространство образовательных программ', program_goal_placeholder: 'Опишите цель образовательной программы...', editing: 'Редактирование', title: 'Название', dependent_courses: 'Зависимые дисциплины (постреквизиты)', no_dependent_courses: 'Зависимых дисциплин нет', prerequisite_search_placeholder: 'Найти пререквизит по коду или названию...', import_courses: 'Импорт дисциплин', file: 'Файл', import: 'Импортировать', add_course_manually: 'Добавить дисциплину вручную', course_code: 'Код дисциплины', description: 'Описание', short_course_description: 'Краткое описание дисциплины...', saving: 'Сохранение...', add_course: 'Добавить дисциплину', auto_assign_requisites: 'Автоматически назначить пре- и постреквизиты', auto_assign_requisites_description: 'Система анализирует дисциплины выбранной области и предлагает связи с учётом тем, последовательности и рекомендуемых семестров.', will_process_courses: 'Будет обработано дисциплин: {count}', requisites_updated: 'Обновлено {updated} из {total} дисциплин. Обновите таблицу.', error: 'Ошибка', apply: 'Применить', close: 'Закрыть',
        semantic_progression: 'Смысловое продолжение', deep_connections: 'Глубоких связей',
        formal_prerequisite: 'Формальный пререквизит', competency_connection: 'Развитие общей компетенции',
        incoming_connections: 'Входящих связей', outgoing_connections: 'Исходящих связей', connected_through_lo: 'Связано через LO',
        learning_trajectory: 'Траектория обучения', scroll_through_program: 'Пролистайте путь студента по семестрам', retry_graph_loading: 'Повторить загрузку графа', repository_source_short: 'репозиторий', plan_inferred_short: 'выведено в плане', graph_text_version: 'Текстовая версия графа', connections: 'Связи', prerequisite_relation: 'Пререквизит', repository_confirmed: 'Подтверждено репозиторием', plan_inferred: 'Выведено алгоритмом для этого плана',
        scroll_graph_hint: 'Слева — дисциплины этапа, в центре — связи, справа — получаемые знания и умения.',
        show_all_connections: 'Все связи', stage: 'Этап', current_stage: 'Текущий этап', result_of_stage: 'Результат этапа',
        create_thematic_plan: 'Создать тематический план', course_syllabus: 'Рабочая программа дисциплины (Syllabus)',
        back_to_graph: 'Назад к графу', academic_weeks: 'Учебных недель', contact_share_percent: 'Доля контактной работы, %',
        recalculate: 'Пересчитать', print_or_pdf: 'Печать / сохранить PDF', total_hours: 'Всего часов',
        contact_hours: 'Контактные часы', independent_hours: 'Самостоятельная работа', lecture_hours: 'Лекции',
        practical_hours: 'Практические/лабораторные', course_description: 'Описание дисциплины', thematic_plan: 'Тематический план',
        week: 'Неделя', topic: 'Тема', lectures_short: 'Лек.', practice_short: 'Практ.', independent_short: 'СРС',
        total: 'Итого', hours_match: 'Часы сходятся', hours_do_not_match: 'Часы не сходятся',
        important_assumptions: 'Важно', credit_30_hours_rule: 'Один кредит равен 30 часам полной учебной нагрузки.',
        institution_template_note: 'Соотношение контактной и самостоятельной работы задаётся шаблоном конкретного вуза.',
        expert_review_required: 'Перед утверждением документ должен проверить преподаватель или методист.',
        semester_competency_report: 'Что студент умеет после семестра',
        semester_competency_explanation: 'Справка построена только по завершённым дисциплинам и подтверждённым результатам обучения.',
        after_semester: 'После семестра', completed_courses: 'Завершено дисциплин', confirmed_program_los: 'Подтверждённые LO',
        student_can_now: 'Освоенные знания и умения', new_evidence_this_semester: 'Новые подтверждения LO в этом семестре',
        no_new_program_lo_evidence: 'Новых подтверждений LO в этом семестре нет.', next_unlocked_courses: 'Какие дисциплины становятся доступны дальше',
        prerequisite_graph: 'Граф пре- и постреквизитов', open_prerequisite_graph: 'Открыть граф связей',
        fit_graph: 'Показать весь граф', reset_view: 'Сбросить выделение', graph_has_cycles: 'Обнаружен цикл — требуется исправление',
        graph_no_cycles: 'Циклов нет', graph_no_plan: 'Сначала постройте варианты учебного плана', semester_short: 'сем.',
        no_description: 'Описание пока не заполнено.', none: 'Нет', no_data: 'Данные пока не заполнены.',
        duration_years: 'Продолжительность программы, лет', duration_hint: '{semesters} семестров, рекомендуемый объём — {credits} кредитов.',
        suggest_three_goals: 'Предложить 3 цели', enter_name_first: 'Сначала введите название программы.', choose_goal: 'Выберите подходящую цель',
        recommended_best: 'Рекомендуемый вариант', option: 'Вариант', select_goal: 'Выбрать эту цель', selected: 'Выбрано',
        suggest_learning_outcomes: 'Предложить результаты обучения', suggested_learning_outcomes: 'Предложенные результаты обучения',
        add_all: 'Добавить все', add: 'Добавить', added: 'Добавлено', new_program: 'новая образовательная программа', primary_domain: 'основная предметная область', secondary_domain: 'смежная предметная область',
        program_name_example: 'например: Киберследователь', domain1_example: 'например: кибербезопасность', domain2_example: 'например: цифровая криминалистика', lo_placeholder: 'LO{number}: опишите измеримый результат обучения...',
        lang_ru: 'Русский', lang_kk: 'Казахский', lang_en: 'Английский',
        epvo_sync_summary: 'CEER: добавлено дисциплин — {created}, связано с существующими — {linked}, источник — {scope}.',
        secondary_epvo_scope: 'Второе направление экспертной базы', secondary_epvo_scope_hint: 'Для междисциплинарной программы дисциплины подтягиваются из двух разных направлений/групп.', secondary_scope_required: 'Выберите второе направление и группу ОП, отличные от первого.',
        goal_template_recommended: 'Подготовить компетентных специалистов программы «{name}», способных интегрировать знания в областях «{domain1}» и «{domain2}», решать профессиональные задачи, ответственно применять современные технологии и развиваться в течение всей жизни.',
        goal_template_practical: 'Обеспечить практико-ориентированную подготовку выпускников программы «{name}» для проектирования, внедрения и оценки решений на стыке областей «{domain1}» и «{domain2}».',
        goal_template_research: 'Сформировать у выпускников программы «{name}» исследовательские и аналитические компетенции для создания инновационных решений в областях «{domain1}» и «{domain2}».',
        lo_template_1: 'Применять основные теории, методы и инструменты области «{domain1}» для решения профессиональных задач.',
        lo_template_2: 'Использовать современные технологии и практики области «{domain2}» в прикладных проектах.',
        lo_template_3: 'Интегрировать знания областей «{domain1}» и «{domain2}» при проектировании комплексных решений.',
        lo_template_4: 'Анализировать данные, риски и ограничения решений на стыке областей «{domain1}» и «{domain2}».',
        lo_template_5: 'Работать в команде, ясно представлять результаты и обосновывать профессиональные решения.',
        lo_template_6: 'Соблюдать этические нормы, требования безопасности, защиты данных и устойчивого развития.',
        login: 'Войти', logout: 'Выйти', password: 'Пароль', loading: 'Загрузка...', creating: 'Создание…', large_views_loading_hint: 'Большие графы и отчёты могут открываться несколько секунд.', program_credit_target_hint: 'План должен набрать {credits} кредитов. Допуск технического балансирования: +{tolerance} кредита.', credit_tolerance: 'Допуск итоговых кредитов', credit_tolerance_hint: 'Для стандартной ОП обычно достаточно 3 кредитов; система стремится к точному объёму.', error: 'Ошибка', network_error: 'Ошибка сети или сервера', invalid_credentials: 'Неверный адрес электронной почты или пароль', cancel: 'Отмена',
        save: 'Сохранить', edit: 'Редактировать', back: 'Назад', next: 'Далее', dashboard: 'Панель управления',
        repository: 'Репозиторий дисциплин', projects: 'Проекты образовательных программ', create_project: 'Создать проект',
        total_projects: 'Всего проектов', total_courses: 'Дисциплин в репозитории', active_plans: 'Активных планов',
        no_projects: 'Проектов пока нет. Создайте первый проект.', date_created: 'Дата создания', active: 'Активен', draft: 'Черновик',
        program_name: 'Название программы', domains: 'Предметные области', domain: 'Предметная область', status: 'Статус',
        actions: 'Действия', open: 'Открыть', delete: 'Удалить', confirm_delete: 'Удалить этот проект вместе со всеми версиями и планами?', confirm_delete_course: 'Удалить эту дисциплину?',
        project_deleted: 'Проект удалён', project_delete_error: 'Не удалось удалить проект', course_repository: 'Репозиторий дисциплин',
        course_repository_desc: 'Управление дисциплинами, импорт, генерация и связи', create_project_desc: 'Создать новую образовательную программу по шагам',
        course_code: 'Код', course_title: 'Название', course_domain: 'Предметная область', credits: 'Кредиты', prerequisites: 'Пререквизиты',
        postrequisites: 'Постреквизиты', cycle_component: 'Компонент цикла', import: 'Импорт', search: 'Поиск', all_domains: 'Все области',
        basic_info: 'Основная информация', step: 'Шаг', program_goal: 'Цель программы', learning_outcomes: 'Результаты обучения',
        add_lo: 'Добавить результат обучения', add_lo_description: 'Укажите измеримые результаты обучения программы', constraints: 'Ограничения',
        num_semesters: 'Количество семестров', total_credits: 'Всего кредитов', max_credits_semester: 'Кредитов в семестре',
        min_domain_percent: 'Минимальная доля области, %', allow_new_courses: 'Разрешить новые дисциплины', max_new_courses: 'Максимум новых дисциплин',
        review_data: 'Проверка данных', plan_builder: 'Конструктор учебного плана', generate_variants: 'Построить варианты', variant: 'Вариант',
        semester: 'Семестр', semester_lo: 'Результаты обучения семестра', evidence_courses: 'Дисциплины-подтверждения', connection_strength: 'Сила связи', programme_outcome: 'Результат программы', course_outcome: 'Результат дисциплины', no_semester_lo_evidence: 'В этом семестре пока нет подтверждённых связей с результатами программы.', activate: 'Сделать активным', deactivate: 'Активный план',
        activate_plan_hint: 'После выбора проект перестанет быть черновиком и появится на главной как активный.',
        activate_invalid_plan_hint: 'Этот вариант нельзя активировать: сначала исправьте жёсткие нарушения плана.',
        activate_plan_with_warnings_hint: 'Вариант можно выбрать как активный, но проверки качества всё ещё показывают жёсткие замечания.',
        active_plan_hint: 'Этот вариант утверждён и используется как действующий учебный план.',
        activation_success: 'Готово: вариант выбран, проект опубликован и теперь имеет статус «Активен».',
        mandatory: 'обязательный компонент', university: 'вузовский компонент', elective: 'компонент по выбору',
        variant_a_desc: '(максимум покрытия LO)', variant_b_desc: '(минимум новых дисциплин)', variant_c_desc: '(баланс и минимум повторов)',
        analytics: 'Аналитика', check_coverage: 'Анализ покрытия LO',
        check_coverage_description: 'Проверить, насколько дисциплины покрывают результаты обучения', coverage_percent: 'Покрытие',
        covered: 'Покрыто', not_covered: 'Не покрыто', verification: 'Проверка плана', feasible: 'Допустимый план', yes: 'Да', no: 'Нет', minimum: 'Минимум',
        prerequisite_violations: 'Нарушения пререквизитов', load_violations: 'Нарушения нагрузки', min_lo_coverage: 'Минимальное покрытие LO',
        evidence_count: 'Количество подтверждений', redundancy: 'Избыточность', 'Changes saved': 'Изменения сохранены',
        'Error saving': 'Не удалось сохранить', 'Error saving weights': 'Не удалось сохранить приоритеты', 'Course deleted': 'Дисциплина удалена',
        'Error deleting': 'Не удалось удалить', 'Import successful!': 'Импорт завершён',
        'Bridge module ID not found. Please regenerate.': 'Идентификатор bridge-модуля не найден. Сгенерируйте модули заново.',
        knowledge_graph: 'Граф знаний Curriculum-KAG', build_graph: 'Построить граф', rebuild_graph: 'Перестроить граф',
        graph_description: 'Граф связывает дисциплины, пререквизиты и результаты обучения и улучшает поиск кандидатов.',
        embedding_mode: 'Режим векторизации', mixed_index: 'Обнаружен смешанный индекс', reindex_all: 'Переиндексировать всё',
        reindexing: 'Переиндексация...', courses_label: 'Дисциплины', total_edges: 'Всего связей', prerequisite_links: 'Пререквизиты',
        similarity_links: 'Семантические связи', lo_coverage_links: 'Связи с LO', graph_built: 'Граф построен',
        graph_not_built: 'Граф ещё не построен. Постройте его перед анализом и генерацией плана.',
        bridge_suggestions: 'Предложения bridge-модулей', generate_bridge: 'Создать bridge-модули', generating: 'Создание...',
        bridge_description: 'Если существующих дисциплин недостаточно, система предлагает междисциплинарный модуль для закрытия пробела.',
        no_gaps: 'Пробелов нет: все результаты обучения покрыты.', topics: 'Темы', assessment: 'Оценивание',
        promoted: 'Добавлено в репозиторий', promote_course: 'Подтвердить и добавить дисциплину',
        promote_desc: 'После подтверждения модуль станет доступен для новых вариантов плана.',
        lo_achievability: 'Анализ достижимости результатов обучения', analyze_ai: 'Проанализировать с AI', analyzing: 'Анализ...',
        achievability_description: 'AI проверяет реалистичность LO с учётом текущего набора дисциплин и предлагает следующие действия.',
        achievability_score: 'Оценка достижимости', per_lo_recommendations: 'Рекомендации по LO', all_los_good: 'Все LO сформулированы и покрыты.',
        what_next: 'Что делать дальше?', clarify_vague_los: 'Уточните LO, отмеченные как слишком общие.',
        generate_missing_los: 'Создайте bridge-модули для непокрытых LO.', review_promote: 'Проверьте модули и подтвердите только подходящие.',
        regenerate_variants_hint: 'Заново постройте варианты: существующий план автоматически не меняется.',
        generate_missing_modules: '1. Создать недостающие модули', edit_los: 'Редактировать LO', open_plan_builder: '3. Открыть конструктор плана',
        save_priorities: 'Сохранить приоритеты', priorities_saved: 'Приоритеты сохранены. Теперь заново постройте варианты.',
        international_quality: 'Международный чек-лист качества', recommendation: 'Рекомендация', bridge_label: 'Bridge-модуль',
        optimizer: 'Способ построения', optimizer_parameters: 'популяция {population}, поколений {generations}',
        apply_all_quality_improvements: 'Применить все улучшения', applying_quality_improvements: 'Применяем улучшения и перестраиваем планы...',
        quality_improvements_applied: 'Все доступные улучшения применены. Варианты A/B/C перестроены.', quality_improvements_error: 'Не удалось применить улучшения',
        'Outcome-based curriculum mapping': 'Связь учебного плана с результатами обучения',
        'Structured progression and prerequisite integrity': 'Последовательность обучения и целостность пререквизитов',
        'Domain relevance control': 'Соответствие предметным областям',
        'Integrated interdisciplinary curriculum': 'Интегрированная междисциплинарная программа',
        'Assessment alignment': 'Согласованность методов оценивания',
        'Continuous improvement and expert-in-the-loop learning': 'Непрерывное улучшение с участием эксперта',
        'Ensure every programme LO has explicit course or bridge-module evidence.': 'Добавьте для каждого LO явное подтверждение дисциплиной или bridge-модулем.',
        'Fix prerequisite order, semester load, or total-credit violations.': 'Исправьте порядок пререквизитов, нагрузку семестров или сумму кредитов.',
        'Remove unrelated courses or replace them with domain-specific/bridge modules.': 'Удалите нерелевантные дисциплины или замените их профильными/bridge-модулями.',
        'Review only the unsupported professional courses; RK mandatory components, practices, and final attestation are not removed in KZ mode.': 'Проверьте только неподтверждённые профильные дисциплины; обязательные компоненты РК, практики и итоговая аттестация не удаляются в режиме ГОСО РК.',
        'Add bridge modules that connect the two programme domains.': 'Добавьте bridge-модули, связывающие две области программы.',
        'Add assessment methods for courses/modules to support outcome-attainment evidence.': 'Добавьте методы оценивания, подтверждающие достижение результатов обучения.',
        'Use Promote to Course and regenerate variants to document the learning loop.': 'Подтвердите подходящие модули и заново постройте варианты, чтобы зафиксировать цикл улучшения.',
        build_error: 'Не удалось построить план', activate_error: 'Не удалось выбрать план',
        graph_rebuilt_title: 'Граф знаний обновлён', graph_rebuilt_text: 'Граф обновил данные для поиска и анализа. Существующие планы не изменены; при необходимости постройте варианты заново.',
        bridge_generated_title: 'Bridge-модули созданы', bridge_generated_text: 'Это предложения, план пока не изменён. Проверьте модули, подтвердите подходящие и заново постройте варианты.',
        kb_updated_title: 'База знаний обновлена', kb_updated_text: 'Модуль добавлен в репозиторий. Заново постройте варианты, чтобы он мог попасть в план.',
        analysis_completed_title: 'Анализ LO завершён', analysis_completed_text: 'Это диагностический отчёт. Он не меняет план автоматически: выполните предложенные действия ниже.',
        promotion_error: 'Не удалось добавить bridge-модуль', open_regenerate: 'Открыть конструктор / построить заново', hide: 'Скрыть',
        plan_label: 'План', min_lo_label: 'мин. LO', uncovered_los: 'Непокрытые LO (пробелы)', page_effect: 'Как эта страница влияет на учебный план',
        graph_effect: 'Перестройка графа обновляет поиск, но не переписывает существующий план.',
        bridge_effect: 'Создание bridge-модулей даёт предложения для слабых LO; это ещё не дисциплины.',
        promote_effect: 'Подтверждение добавляет bridge-модуль в репозиторий и обновляет базу знаний.',
        regenerate_effect: 'Чтобы новая дисциплина появилась в плане, нужно заново построить варианты.',
        Ready: 'Готово', 'Needs Improvement': 'Требуется улучшение', 'Critical Gaps': 'Критические пробелы',
        'on track': 'в норме', 'needs courses': 'нужны дисциплины', 'too vague': 'слишком общий', critical: 'критично'
    },
    kk: {
        select_education_area: 'Білім беру саласын таңдаңыз',
        ru: 'Орысша', kk: 'Қазақша', en: 'English',
        ai_translation: 'ЖИ аудармасы, автоматты тексеруден өтті',
        dataset_passport: 'Деректер жиынтығының паспорты', model_benchmark: 'Модельдерді салыстыру',
        research_dashboard: 'Деректер және модель сапасы', research_dashboard_desc: 'Dataset Passport, бақылау жиынтықтары және модель метрикалары', epvo_programs: 'Сараптамалық базадағы бағдарламалар', normalized_courses: 'Нормаланған пәндер', expert_links: 'Сараптамалық байланыстар', independent_test: 'Тәуелсіз тест жиынтығы', model: 'Модель', examples: 'Мысалдар',
        feedback_confirmed: 'Растау', feedback_weak: 'Әлсіз байланыс', feedback_incorrect: 'Қате',
        ai_prediction: 'ЖИ болжамы', metrics_refresh: 'Жоспар метрикаларын жаңарту қажет', metrics_refresh_desc: 'Бұл нұсқа валидатордың алдыңғы нұсқасымен жасалған. Кредиттерді, жүктемені, пререквизиттерді және LO дәлелдерін қайта тексеру үшін нұсқаны қайта құрыңыз.', rebuild_verify: 'Қайта құрып, тексеру', fix_quality: 'Ретті, жүктемені және кредиттерді түзету', epvo_courses: 'Жоспардағы ЕПВО пәндері', typical_courses: 'типтік пәндер', expert_links_label: 'сараптамалық байланыстар', full_epvo_analysis: 'ЕПВО толық талдауы', suspicious_courses: 'Күмәнді пәндер', find_all_replacements: 'Көрінетіндердің бәріне ауыстыру табу', find_replacements: '3 ауыстыруды таңдау', reason_wrong_level: 'білім деңгейіне сәйкес емес', reason_not_core: 'бағдарлама өзегі емес', reason_weak_evidence: 'LO дәлелі әлсіз', reason_too_early: 'тым ерте', best_link: 'Ең жақсы байланыс', confirm_link: 'Байланысты растау', keep_in_plan: 'Жоспарда қалдыру', mark_replacement: 'Ауыстыруға белгілеу', replacing: 'Ауыстыру…', confirm_replacement: 'Ауыстыруды растау', no_equivalent: 'Сәйкес балама әлі жоқ.', professional_los: 'Кәсіби ОН', recommended_semester: 'ұсынылатын семестр', system_not_blocking: 'Жүйе қарауды бұғаттамайды, бірақ мұндай пәндерді ауыстыру немесе сарапшымен растау керек.', searching_replacements: 'Ауыстырулар ізделуде…', search_replacements: 'Іздеу…', replace_on_regeneration_checked: '✓ Қайта құруда ауыстыру', replacement_preview_done: 'Ауыстыруды таңдау {seconds}s ішінде орындалды.',
        compare_epvo: 'Сараптамалық базамен салыстыру', epvo_reference_courses: 'CEER таңдауындағы пәндер', present_in_plan: 'Жоспарда бар', missing_from_plan: 'Жоқ пәндер', typical_epvo_courses: 'Сараптамалық базаның типтік пәндері', source_programs: 'Дереккөз бағдарламалар', present: 'Бар', missing: 'Жоқ',
        select_direction: 'Даярлау бағытын таңдаңыз', select_group: 'ББ тобын таңдаңыз',
        building_plan: 'Жоспар құрылуда',
        education_level: 'Білім деңгейі', regulatory_profile: 'Нормативтік профиль', ruleset_version: 'Ruleset редакциясы', goso_compliance_title: 'Қазақстан Республикасының МЖМБС сәйкестігі', status_label: 'Күйі', goso_compliant: 'сәйкес', goso_violations: 'бұзушылықтар бар', mandatory_credits: 'Міндетті кредиттер', automatic_quality_audit: 'Жоспар сапасын автоматты тексеру', quality_passed: 'Жоспар ОН байланыстары мен семестр реттілігі тексерісінен өтті.', quality_needs_corrections: 'Жоспар сарапшылық бекітуге дейін түзетуді қажет етеді.', semester_load_band: 'Семестрлік жүктеме: мақсат (рұқсат етілген аралық)', structural_prerequisites: 'Құрылымдық пререквизиттер', los_without_real_course: 'Нақты пәнсіз ОН', weak_courses: 'Әлсіз пәндер', semester_misplacements: 'Орынсыз семестр', best_real_link: 'ең жақсы нақты байланыс', recommended: 'ұсынылады', bachelor: 'Бакалавриат', master: 'Магистратура', doctorate: 'Докторантура', education_area: 'Білім беру саласы', direction_code: 'Даярлау бағыты', group_code: 'Білім беру бағдарламаларының тобы', program_type: 'Бағдарлама түрі', standard_program: 'Стандартты', interdisciplinary_program: 'Пәнаралық', joint_program: 'Бірлескен', instruction_language: 'Оқыту тілі',
        curriculum_workspace: 'Білім беру бағдарламаларының жұмыс кеңістігі', program_goal_placeholder: 'Білім беру бағдарламасының мақсатын сипаттаңыз...', editing: 'Өңдеу', title: 'Атауы', dependent_courses: 'Тәуелді пәндер (постреквизиттер)', no_dependent_courses: 'Тәуелді пәндер жоқ', prerequisite_search_placeholder: 'Пререквизитті код немесе атау бойынша табу...', import_courses: 'Пәндерді импорттау', file: 'Файл', import: 'Импорттау', add_course_manually: 'Пәнді қолмен қосу', course_code: 'Пән коды', description: 'Сипаттама', short_course_description: 'Пәннің қысқаша сипаттамасы...', saving: 'Сақталуда...', add_course: 'Пәнді қосу', auto_assign_requisites: 'Пре- және постреквизиттерді автоматты тағайындау', auto_assign_requisites_description: 'Жүйе таңдалған бағыттағы пәндерді талдап, тақырыптар, реттілік және ұсынылған семестрлер негізінде байланыстарды ұсынады.', will_process_courses: 'Өңделетін пәндер саны: {count}', requisites_updated: '{total} пәннің {updated} пәні жаңартылды. Кестені жаңартыңыз.', error: 'Қате', apply: 'Қолдану', close: 'Жабу',
        semantic_progression: 'Мағыналық жалғастық', deep_connections: 'Терең байланыстар',
        formal_prerequisite: 'Ресми пререквизит', competency_connection: 'Ортақ құзыреттілікті дамыту',
        incoming_connections: 'Кіріс байланыстар', outgoing_connections: 'Шығыс байланыстар', connected_through_lo: 'LO арқылы байланыс',
        learning_trajectory: 'Оқу траекториясы', scroll_through_program: 'Студент жолын семестр бойынша қараңыз', retry_graph_loading: 'Графты қайта жүктеу', repository_source_short: 'репозиторий', plan_inferred_short: 'жоспарда шығарылды', graph_text_version: 'Графтың мәтіндік нұсқасы', connections: 'Байланыстар', prerequisite_relation: 'Пререквизит', repository_confirmed: 'Репозиторий расталған', plan_inferred: 'Осы жоспар үшін алгоритм шығарған',
        scroll_graph_hint: 'Сол жақта пәндер, ортасында байланыстар, оң жақта алынатын білім мен дағдылар.',
        show_all_connections: 'Барлық байланыс', stage: 'Кезең', current_stage: 'Ағымдағы кезең', result_of_stage: 'Кезең нәтижесі',
        create_thematic_plan: 'Тақырыптық жоспар құру', course_syllabus: 'Пәннің жұмыс бағдарламасы (Syllabus)',
        back_to_graph: 'Графқа оралу', academic_weeks: 'Оқу аптасы', contact_share_percent: 'Байланыс жұмысының үлесі, %',
        recalculate: 'Қайта есептеу', print_or_pdf: 'Басып шығару / PDF', total_hours: 'Жалпы сағат',
        contact_hours: 'Байланыс сағаты', independent_hours: 'Өзіндік жұмыс', lecture_hours: 'Дәріс',
        practical_hours: 'Практика/зертхана', course_description: 'Пән сипаттамасы', thematic_plan: 'Тақырыптық жоспар',
        week: 'Апта', topic: 'Тақырып', lectures_short: 'Дәр.', practice_short: 'Прак.', independent_short: 'СӨЖ',
        total: 'Барлығы', hours_match: 'Сағаттар сәйкес', hours_do_not_match: 'Сағаттар сәйкес емес',
        important_assumptions: 'Маңызды', credit_30_hours_rule: 'Бір кредит толық оқу жүктемесінің 30 сағатына тең.',
        institution_template_note: 'Байланыс және өзіндік жұмыс арақатынасын ЖОО шаблоны белгілейді.',
        expert_review_required: 'Бекіту алдында құжатты оқытушы немесе әдіскер тексереді.',
        semester_competency_report: 'Студент семестрден кейін не істей алады',
        semester_competency_explanation: 'Анықтама тек аяқталған пәндер мен расталған оқу нәтижелеріне негізделген.',
        after_semester: 'Семестрден кейін', completed_courses: 'Аяқталған пәндер', confirmed_program_los: 'Расталған LO',
        student_can_now: 'Игерілген білім мен дағдылар', new_evidence_this_semester: 'Осы семестрдегі жаңа LO дәлелдері',
        no_new_program_lo_evidence: 'Осы семестрде жаңа LO дәлелі жоқ.', next_unlocked_courses: 'Келесі қолжетімді пәндер',
        prerequisite_graph: 'Пре- және постреквизиттер графы', open_prerequisite_graph: 'Байланыстар графын ашу',
        fit_graph: 'Толық графты көрсету', reset_view: 'Таңдауды тазарту', graph_has_cycles: 'Цикл табылды — түзету қажет',
        graph_no_cycles: 'Цикл жоқ', graph_no_plan: 'Алдымен оқу жоспарының нұсқаларын құрыңыз', semester_short: 'сем.',
        no_description: 'Сипаттама толтырылмаған.', none: 'Жоқ', no_data: 'Дерек толтырылмаған.',
        duration_years: 'Бағдарлама ұзақтығы, жыл', duration_hint: '{semesters} семестр, ұсынылатын көлемі — {credits} кредит.',
        suggest_three_goals: '3 мақсат ұсыну', enter_name_first: 'Алдымен бағдарлама атауын енгізіңіз.', choose_goal: 'Мақсатты таңдаңыз',
        recommended_best: 'Ұсынылатын нұсқа', option: 'Нұсқа', select_goal: 'Осы мақсатты таңдау', selected: 'Таңдалды',
        suggest_learning_outcomes: 'Оқу нәтижелерін ұсыну', suggested_learning_outcomes: 'Ұсынылған оқу нәтижелері',
        add_all: 'Барлығын қосу', add: 'Қосу', added: 'Қосылды', new_program: 'жаңа білім беру бағдарламасы', primary_domain: 'негізгі пәндік сала', secondary_domain: 'қосымша пәндік сала',
        program_name_example: 'мысалы: Кибертергеуші', domain1_example: 'мысалы: киберқауіпсіздік', domain2_example: 'мысалы: цифрлық криминалистика', lo_placeholder: 'LO{number}: өлшенетін оқу нәтижесін сипаттаңыз...',
        lang_ru: 'Орыс тілі', lang_kk: 'Қазақ тілі', lang_en: 'Ағылшын тілі',
        epvo_sync_summary: 'CEER: қосылған пәндер — {created}, бар пәндермен байланыстырылды — {linked}, дереккөзі — {scope}.',
        secondary_epvo_scope: 'Сараптамалық базаның екінші бағыты', secondary_epvo_scope_hint: 'Пәнаралық бағдарлама үшін пәндер екі түрлі бағыттан/топтан алынады.', secondary_scope_required: 'Біріншіден бөлек екінші бағыт пен ББ тобын таңдаңыз.',
        goal_template_recommended: '«{name}» бағдарламасы бойынша «{domain1}» және «{domain2}» салаларының білімін біріктіріп, кәсіби міндеттерді жауапкершілікпен шеше алатын мамандар даярлау.',
        goal_template_practical: '«{name}» бағдарламасының түлектерін «{domain1}» және «{domain2}» тоғысындағы шешімдерді жобалауға және бағалауға даярлау.',
        goal_template_research: '«{name}» түлектерінде «{domain1}» және «{domain2}» салалары үшін инновациялық шешімдер жасауға қажетті зерттеу құзыреттерін қалыптастыру.',
        lo_template_1: '«{domain1}» саласының теориялары мен құралдарын кәсіби міндеттерге қолдану.', lo_template_2: '«{domain2}» саласының заманауи технологияларын қолданбалы жобаларда пайдалану.',
        lo_template_3: '«{domain1}» және «{domain2}» білімдерін кешенді шешімдерде біріктіру.', lo_template_4: '«{domain1}» және «{domain2}» тоғысындағы деректерді, тәуекелдерді және шектеулерді талдау.',
        lo_template_5: 'Командада жұмыс істеу және кәсіби шешімдерді негіздеу.', lo_template_6: 'Этика, қауіпсіздік, деректерді қорғау және тұрақты даму талаптарын сақтау.',
        login: 'Кіру', logout: 'Шығу', password: 'Құпия сөз', loading: 'Жүктелуде...', creating: 'Жасалуда…', large_views_loading_hint: 'Үлкен графиктер мен есептердің ашылуына бірнеше секунд кетуі мүмкін.', program_credit_target_hint: 'Жоспарда {credits} кредит болуы керек. Техникалық теңгерімдеу рұқсаты: +{tolerance} кредит.', credit_tolerance: 'Жалпы кредиттер рұқсаты', credit_tolerance_hint: 'Стандартты бағдарлама үшін әдетте 3 кредит жеткілікті; жүйе дәл көлемге ұмтылады.', error: 'Қате', network_error: 'Желі немесе сервер қатесі', invalid_credentials: 'Электрондық пошта мекенжайы немесе құпия сөз қате', cancel: 'Бас тарту',
        save: 'Сақтау', edit: 'Өңдеу', back: 'Артқа', next: 'Келесі', dashboard: 'Басқару панелі', repository: 'Пәндер репозиторийі',
        projects: 'Білім беру бағдарламалары', create_project: 'Жоба құру', total_projects: 'Жобалар саны', total_courses: 'Пәндер саны',
        active_plans: 'Белсенді жоспарлар', no_projects: 'Жобалар жоқ. Бірінші жобаны құрыңыз.', date_created: 'Құрылған күні',
        active: 'Белсенді', draft: 'Жоба', program_name: 'Бағдарлама атауы', domains: 'Пәндік салалар', domain: 'Пәндік сала',
        status: 'Күйі', actions: 'Әрекеттер', open: 'Ашу', delete: 'Жою', confirm_delete_course: 'Бұл пәнді жою керек пе?', course_repository: 'Пәндер репозиторийі',
        course_code: 'Код', course_title: 'Атауы', course_domain: 'Пәндік сала', credits: 'Кредиттер', prerequisites: 'Пререквизиттер',
        postrequisites: 'Постреквизиттер', import: 'Импорт', search: 'Іздеу', all_domains: 'Барлық салалар', basic_info: 'Негізгі ақпарат',
        step: 'Қадам', program_goal: 'Бағдарлама мақсаты', learning_outcomes: 'Оқу нәтижелері', add_lo: 'Оқу нәтижесін қосу',
        constraints: 'Шектеулер', num_semesters: 'Семестрлер саны', total_credits: 'Барлық кредиттер', plan_builder: 'Оқу жоспарын құрастыру',
        generate_variants: 'Нұсқаларды құру', variant: 'Нұсқа', semester: 'Семестр', semester_lo: 'Семестрдің оқу нәтижелері', evidence_courses: 'Растайтын пәндер', connection_strength: 'Байланыс күші', programme_outcome: 'Бағдарлама нәтижесі', course_outcome: 'Пән нәтижесі', no_semester_lo_evidence: 'Бұл семестрде бағдарлама нәтижелерімен расталған байланыстар әзірге жоқ.', activate: 'Белсенді ету', deactivate: 'Белсенді жоспар',
        activate_plan_hint: 'Таңдағаннан кейін жоба нобай мәртебесінен шығып, белсенді болады.', activate_invalid_plan_hint: 'Бұл нұсқаны белсенді етуге болмайды: алдымен жоспардағы қатаң бұзушылықтарды түзетіңіз.', activate_plan_with_warnings_hint: 'Нұсқаны белсенді етіп таңдауға болады, бірақ сапа тексерістері әлі қатаң ескертулер көрсетеді.', active_plan_hint: 'Бұл нұсқа қолданыстағы оқу жоспары ретінде бекітілді.',
        activation_success: 'Дайын: нұсқа таңдалды және жоба белсенді мәртебесіне өтті.',
        verification: 'Жоспарды тексеру', feasible: 'Орындалатын жоспар', yes: 'Иә', no: 'Жоқ', minimum: 'Минимум',
        prerequisite_violations: 'Пререквизит бұзушылықтары', load_violations: 'Жүктеме бұзушылықтары',
        min_lo_coverage: 'LO ең төмен қамтылуы', evidence_count: 'Дәлелдер саны', redundancy: 'Артықтық', covered: 'Қамтылған', not_covered: 'Қамтылмаған',
        cycle: 'Цикл', cycle_estimate: 'жүйе есебі', component: 'Компонент', source: 'Дереккөз', source_rk_mandatory: 'ҚР міндетті пәні', source_ai_confirmed: 'ЖИ расталған ауыстыру', source_bridge: 'bridge-модуль', source_repository: 'пәндер репозиторийі', remove_on_regeneration: 'Қайта құру кезінде алынады', replace_on_generation: 'Келесі құруда ауыстыру/алып тастау', goso_protected: 'ҚР МЖМБС міндетті пәні — жоюдан және ауыстырудан қорғалған', why_selected: 'Неге таңдалды?', lo_links: 'Оқу нәтижелерімен байланыс:', effective: 'қорытынды', ai_short: 'ЖИ', epvo_short: 'ЕПВО', bridge_short: 'bridge', weak_link: 'әлсіз байланыс', prereq_title: 'Осы жоспардағы пре- және постреквизиттер', prereq_note: 'Тек ағымдағы жоспар нұсқасында бар пәндер көрсетіледі.', before_course: 'Осы пәнге дейін:', after_course: 'Одан кейін сүйенетін пәндер:', no_prerequisites: 'жоспарда міндетті алдыңғы пәндер жоқ', no_postrequisites: 'ағымдағы жоспарда оны пререквизит ретінде талап ететін пәндер жоқ', semester_short: 'Сем.', semester_title: 'Семестр', credits_lower: 'кредит', explanation_score: 'Пайыздар бір пән мен бір LO байланысына жатады. ЖИ — мәтіндер бойынша модель болжамы. ЕПВО — сол байланыстың сараптамалық деректердегі қолдауы. Олар қосылмайды.', explanation_read: 'Оқу тәртібі: “қорытынды” — пән осы LO-ны жоспарда қаншалықты жабады; “ЖИ” — мәтіндер бойынша модель болжамы; “ЕПВО” — ЕПВО базасындағы ұқсас сараптамалық баға. Бұлар бір байланыстың үш бөлек белгісі, қосылмайды.', explanation_effective: 'Қорытынды — осы пәннің осы ОН-мен байланыс күші. ЖИ — мәтіндер бойынша модель болжамы. ЕПВО — базадағы сараптамалық бағаны қалпына келтіру. Олар қосылмайды.', coverage_sources: 'LO қамту көздері', coverage_sources_desc: 'Қай нәтижелер нақты пәндермен, қайсысы тек bridge-модульдермен жабылғанын көрсетеді.', show_lo_sources: 'LO көздерін көрсету', total_los: 'Барлық LO', real_courses: 'нақты пәндер', weak: 'әлсіз', real_course: 'нақты пән', weak_coverage: 'әлсіз қамту', bridge_assumption: '75% — жобалық bridge қызметтік бағасы, нақты ЕПВО пәнінің сараптамалық бағасы емес.', bridge_in_plan: 'жоспардағы bridge', show_in_plan: 'Жоспарда көрсету',
        'Changes saved': 'Өзгерістер сақталды', 'Error saving': 'Сақтау мүмкін болмады', 'Error saving weights': 'Басымдықтарды сақтау мүмкін болмады',
        'Course deleted': 'Пән өшірілді', 'Error deleting': 'Өшіру мүмкін болмады', 'Import successful!': 'Импорт аяқталды',
        'Bridge module ID not found. Please regenerate.': 'Bridge-модуль идентификаторы табылмады. Қайта жасаңыз.',
        'Outcome-based curriculum mapping': 'Оқу нәтижелерімен байланыс',
        'Structured progression and prerequisite integrity': 'Оқыту реттілігі және пререквизиттердің тұтастығы',
        'Domain relevance control': 'Пәндік салаларға сәйкестік',
        'Integrated interdisciplinary curriculum': 'Интеграцияланған пәнаралық бағдарлама',
        'Assessment alignment': 'Бағалау әдістерінің келісімі',
        'Continuous improvement and expert-in-the-loop learning': 'Сарапшының қатысуымен үздіксіз жетілдіру',
        'Ensure every programme LO has explicit course or bridge-module evidence.': 'Әрбір ОН-ның пән немесе bridge-модуль арқылы нақты дәлелін қамтамасыз етіңіз.',
        'Fix prerequisite order, semester load, or total-credit violations.': 'Пререквизиттер ретін, семестрлік жүктемені немесе кредиттер сомасын түзетіңіз.',
        'Remove unrelated courses or replace them with domain-specific/bridge modules.': 'Сәйкес келмейтін пәндерді алып тастаңыз немесе оларды пәндік/bridge модульдермен ауыстырыңыз.',
        'Review only the unsupported professional courses; RK mandatory components, practices, and final attestation are not removed in KZ mode.': 'Тек расталмаған бейіндік пәндерді тексеріңіз; ҚР міндетті компоненттері, практикалар және қорытынды аттестация ҚР режимінде жойылмайды.',
        'Add bridge modules that connect the two programme domains.': 'Бағдарламаның екі саласын байланыстыратын bridge-модульдерді қосыңыз.',
        'Add assessment methods for courses/modules to support outcome-attainment evidence.': 'Оқу нәтижелеріне қол жеткізуді растайтын бағалау әдістерін қосыңыз.',
        'Use Promote to Course and regenerate variants to document the learning loop.': 'Тиісті модульдерді растап, жаңа нұсқаларды құрыңыз.',
        Ready: 'Дайын', 'Needs Improvement': 'Жақсарту қажет', 'Critical Gaps': 'Маңызды олқылықтар',
        'on track': 'қалыпты', 'needs courses': 'пәндер қажет', 'too vague': 'тым жалпы', critical: 'сыни'
    },
    en: {
        select_education_area: 'Select education area',
        ru: 'Russian', kk: 'Kazakh', en: 'English', Ready: 'Ready', critical: 'critical',
        ai_translation: 'AI translation, passed automatic QA',
        dataset_passport: 'Dataset Passport', model_benchmark: 'Model Benchmark',
        research_dashboard: 'Data and model quality', research_dashboard_desc: 'Dataset Passport, evaluation splits, and model metrics', epvo_programs: 'Expert-repository programmes', normalized_courses: 'Normalized courses', expert_links: 'Expert links', independent_test: 'Independent test split', model: 'Model', examples: 'Examples',
        feedback_confirmed: 'Confirm', feedback_weak: 'Weak link', feedback_incorrect: 'Incorrect',
        ai_prediction: 'AI prediction', metrics_refresh: 'Plan metrics need refresh', metrics_refresh_desc: 'This variant was created by an earlier validator. Rebuild it to recheck credits, workload, prerequisites, and LO evidence.', rebuild_verify: 'Rebuild and verify', fix_quality: 'Fix order, load, and credits', epvo_courses: 'Plan courses from EPVO', typical_courses: 'typical courses', expert_links_label: 'expert links', full_epvo_analysis: 'Full EPVO analysis', suspicious_courses: 'Suspicious courses', find_all_replacements: 'Find replacements for all visible', find_replacements: 'Find 3 replacements', reason_wrong_level: 'wrong degree level', reason_not_core: 'not programme core', reason_weak_evidence: 'weak LO evidence', reason_too_early: 'too early', best_link: 'Best link', confirm_link: 'Confirm link', keep_in_plan: 'Keep in plan', mark_replacement: 'Mark for replacement', replacing: 'Replacing…', confirm_replacement: 'Confirm replacement', no_equivalent: 'No equivalent replacement found yet.', professional_los: 'Professional LOs', recommended_semester: 'recommended semester', system_not_blocking: 'The system does not block viewing, but these courses should be replaced or expert-confirmed.', searching_replacements: 'Searching replacements…', search_replacements: 'Searching…', replace_on_regeneration_checked: '✓ Replace on regeneration', replacement_preview_done: 'Replacement preview completed in {seconds}s.',
        compare_epvo: 'Compare with expert repository', epvo_reference_courses: 'Courses in CEER reference set', present_in_plan: 'Present in plan', missing_from_plan: 'Missing', typical_epvo_courses: 'Typical expert-repository courses', source_programs: 'Source programmes', present: 'Present', missing: 'Missing',
        select_direction: 'Select field of study', select_group: 'Select programme group',
        building_plan: 'Building plan',
        education_level: 'Education level', regulatory_profile: 'Regulatory profile', ruleset_version: 'Ruleset version', goso_compliance_title: 'Kazakhstan state-standard compliance', status_label: 'Status', goso_compliant: 'compliant', goso_violations: 'violations found', mandatory_credits: 'Mandatory credits', automatic_quality_audit: 'Automatic curriculum quality audit', quality_passed: 'The plan passed LO alignment and semester sequencing checks.', quality_needs_corrections: 'The plan needs corrections before expert approval.', semester_load_band: 'Semester load: target (allowed range)', structural_prerequisites: 'Structural prerequisites', los_without_real_course: 'LOs without a real course', weak_courses: 'Weak courses', semester_misplacements: 'Semester misplacements', best_real_link: 'best real link', recommended: 'recommended', bachelor: 'Bachelor', master: 'Master', doctorate: 'Doctorate', education_area: 'Education area', direction_code: 'Field of study', group_code: 'Educational programme group', program_type: 'Programme type', standard_program: 'Standard', interdisciplinary_program: 'Interdisciplinary', joint_program: 'Joint', instruction_language: 'Language of instruction',
        curriculum_workspace: 'Curriculum workspace', program_goal_placeholder: 'Describe the educational programme goal...', editing: 'Editing', title: 'Title', dependent_courses: 'Dependent courses (post-requisites)', no_dependent_courses: 'No dependent courses', prerequisite_search_placeholder: 'Find prerequisite by code or title...', import_courses: 'Import courses', file: 'File', import: 'Import', add_course_manually: 'Add course manually', course_code: 'Course code', description: 'Description', short_course_description: 'Short course description...', saving: 'Saving...', add_course: 'Add course', auto_assign_requisites: 'Automatically assign pre- and post-requisites', auto_assign_requisites_description: 'The system analyzes courses in the selected domain and proposes links based on topics, progression, and recommended semesters.', will_process_courses: 'Courses to process: {count}', requisites_updated: 'Updated {updated} of {total} courses. Refresh the table.', error: 'Error', apply: 'Apply', close: 'Close',
        semantic_progression: 'Semantic progression', deep_connections: 'Deep connections',
        formal_prerequisite: 'Formal prerequisite', competency_connection: 'Shared competency development',
        incoming_connections: 'Incoming links', outgoing_connections: 'Outgoing links', connected_through_lo: 'Connected through LOs',
        learning_trajectory: 'Learning Trajectory', scroll_through_program: 'Scroll Through the Student Journey', retry_graph_loading: 'Retry graph loading', repository_source_short: 'repository', plan_inferred_short: 'plan-inferred', graph_text_version: 'Text version of the graph', connections: 'Connections', prerequisite_relation: 'Prerequisite', repository_confirmed: 'Repository-confirmed', plan_inferred: 'Inferred for this plan',
        scroll_graph_hint: 'Courses on the left, live connections in the center, acquired abilities on the right.',
        show_all_connections: 'All Connections', stage: 'Stage', current_stage: 'Current Stage', result_of_stage: 'Stage Result',
        create_thematic_plan: 'Create Thematic Plan', course_syllabus: 'Course Syllabus',
        back_to_graph: 'Back to Graph', academic_weeks: 'Academic weeks', contact_share_percent: 'Contact work share, %',
        recalculate: 'Recalculate', print_or_pdf: 'Print / Save PDF', total_hours: 'Total hours',
        contact_hours: 'Contact hours', independent_hours: 'Independent work', lecture_hours: 'Lectures',
        practical_hours: 'Practical/laboratory', course_description: 'Course description', thematic_plan: 'Thematic plan',
        week: 'Week', topic: 'Topic', lectures_short: 'Lec.', practice_short: 'Prac.', independent_short: 'Ind.',
        total: 'Total', hours_match: 'Hours match', hours_do_not_match: 'Hours do not match',
        important_assumptions: 'Important', credit_30_hours_rule: 'One credit equals 30 hours of total student workload.',
        institution_template_note: 'The institution template defines the contact/independent work split.',
        expert_review_required: 'A lecturer or methodologist must review the document before approval.',
        semester_competency_report: 'What the Student Can Do After the Semester',
        semester_competency_explanation: 'This report uses only completed courses and evidenced learning outcomes.',
        after_semester: 'After semester', completed_courses: 'Completed courses', confirmed_program_los: 'Confirmed LOs',
        student_can_now: 'Acquired knowledge and skills', new_evidence_this_semester: 'New LO evidence this semester',
        no_new_program_lo_evidence: 'No new program LO evidence this semester.', next_unlocked_courses: 'Courses unlocked next',
        prerequisite_graph: 'Prerequisite and Postrequisite Graph', open_prerequisite_graph: 'Open Relationship Graph',
        fit_graph: 'Fit Entire Graph', reset_view: 'Reset Selection', graph_has_cycles: 'A cycle was detected and must be fixed',
        graph_no_cycles: 'No cycles', graph_no_plan: 'Build curriculum variants first', semester_short: 'sem.',
        no_description: 'No description yet.', none: 'None', no_data: 'No data yet.',
        duration_years: 'Program duration, years', duration_hint: '{semesters} semesters, recommended volume — {credits} credits.',
        suggest_three_goals: 'Suggest 3 Goals', enter_name_first: 'Enter the program name first.', choose_goal: 'Choose a goal',
        recommended_best: 'Recommended option', option: 'Option', select_goal: 'Select this goal', selected: 'Selected',
        cycle: 'Cycle', cycle_estimate: 'system estimate', component: 'Component', source: 'Source', source_rk_mandatory: 'RK mandatory course', source_ai_confirmed: 'AI-confirmed replacement', source_bridge: 'bridge module', source_repository: 'course repository', remove_on_regeneration: 'Will be removed on regeneration', replace_on_generation: 'Replace/remove on next generation', goso_protected: 'RK mandatory course — protected from removal and replacement', why_selected: 'Why selected?', lo_links: 'Learning-outcome links:', effective: 'effective', ai_short: 'AI', epvo_short: 'EPVO', bridge_short: 'bridge', weak_link: 'weak link', prereq_title: 'Pre- and post-requisites in this plan', prereq_note: 'Only courses that are actually present in the current plan variant are shown.', before_course: 'Before this course:', after_course: 'Courses that depend on it:', no_prerequisites: 'no required earlier courses in the plan', no_postrequisites: 'no later courses explicitly require it in this plan', semester_short: 'Sem.', semester_title: 'Semester', credits_lower: 'credits', explanation_score: 'Percentages describe one course-to-LO link. AI is the text-model estimate; EPVO is expert support for the same link. They are not added.', explanation_read: 'How to read: effective is the final plan link strength; AI is the text-model prediction; EPVO is similar expert evidence from EPVO. These are separate signals for one link, not a sum.', explanation_effective: 'Effective is the final strength for this course→LO link. AI is the text model prediction. EPVO is reconstructed expert evidence. They are not added together.', coverage_sources: 'LO coverage sources', coverage_sources_desc: 'Shows which outcomes are covered by real courses and which only by bridge modules.', show_lo_sources: 'Show LO sources', total_los: 'Total LOs', real_courses: 'real courses', weak: 'weak', real_course: 'real course', weak_coverage: 'weak coverage', bridge_assumption: '75% is a planning assumption for a proposed bridge, not an expert EPVO course score.', bridge_in_plan: 'bridge in plan', show_in_plan: 'Show in plan',
        suggest_learning_outcomes: 'Suggest Learning Outcomes', suggested_learning_outcomes: 'Suggested Learning Outcomes',
        add_all: 'Add All', add: 'Add', added: 'Added', new_program: 'new educational program', primary_domain: 'primary domain', secondary_domain: 'secondary domain',
        program_name_example: 'e.g., Cyber Investigator', domain1_example: 'e.g., cybersecurity', domain2_example: 'e.g., digital forensics', lo_placeholder: 'LO{number}: Learning outcome description...',
        lang_ru: 'Russian', lang_kk: 'Kazakh', lang_en: 'English',
        epvo_sync_summary: 'CEER: courses added — {created}, linked to existing — {linked}, source — {scope}.',
        secondary_epvo_scope: 'Second expert-repository field', secondary_epvo_scope_hint: 'For interdisciplinary programmes, courses are pulled from two different fields/groups.', secondary_scope_required: 'Choose a second field and programme group different from the first one.',
        goal_template_recommended: 'Prepare competent graduates of “{name}” who can integrate knowledge from “{domain1}” and “{domain2}”, solve professional problems, use modern technologies responsibly, and pursue lifelong learning.',
        goal_template_practical: 'Provide practice-oriented preparation for “{name}” graduates to design, implement, and evaluate solutions at the intersection of “{domain1}” and “{domain2}”.',
        goal_template_research: 'Develop research and analytical competencies in “{name}” graduates for innovative solutions in “{domain1}” and “{domain2}”.',
        lo_template_1: 'Apply core theories, methods, and tools of “{domain1}” to professional problems.', lo_template_2: 'Use modern technologies and practices of “{domain2}” in applied projects.',
        lo_template_3: 'Integrate knowledge from “{domain1}” and “{domain2}” when designing complex solutions.', lo_template_4: 'Analyze data, risks, and constraints at the intersection of “{domain1}” and “{domain2}”.',
        lo_template_5: 'Work in teams, present results clearly, and justify professional decisions.', lo_template_6: 'Follow ethical, security, data-protection, and sustainability requirements.',
        login: 'Login', logout: 'Logout', password: 'Password', loading: 'Loading...', creating: 'Creating…', large_views_loading_hint: 'Large graphs and reports can take a few seconds to open.', program_credit_target_hint: 'The plan must contain {credits} credits. Technical balancing tolerance: +{tolerance} credits.', credit_tolerance: 'Total-credit tolerance', credit_tolerance_hint: 'Three credits are normally sufficient for a standard programme; the system targets the exact volume.', error: 'Error', network_error: 'Network or server error', invalid_credentials: 'Incorrect email or password', cancel: 'Cancel', save: 'Save', edit: 'Edit',
        back: 'Back', next: 'Next', dashboard: 'Dashboard', repository: 'Course Repository', projects: 'Educational Program Projects',
        create_project: 'Create Project', total_projects: 'Total Projects', total_courses: 'Courses in Repository', active_plans: 'Active Plans',
        no_projects: 'No projects yet. Create the first project.', date_created: 'Date Created', active: 'Active', draft: 'Draft',
        program_name: 'Program Name', domains: 'Domains', domain: 'Domain', status: 'Status', actions: 'Actions', open: 'Open', delete: 'Delete', confirm_delete_course: 'Delete this course?',
        confirm_delete: 'Delete this project with all versions and plans?', project_deleted: 'Project deleted', project_delete_error: 'Could not delete project',
        course_repository: 'Course Repository', course_repository_desc: 'Manage courses, imports, generation, and relations',
        create_project_desc: 'Create a new program step by step', course_code: 'Code', course_title: 'Title', course_domain: 'Domain', credits: 'Credits',
        prerequisites: 'Prerequisites', postrequisites: 'Postrequisites', cycle_component: 'Cycle Component', import: 'Import', search: 'Search',
        all_domains: 'All Domains', basic_info: 'Basic Information', step: 'Step', program_goal: 'Program Goal', learning_outcomes: 'Learning Outcomes',
        add_lo: 'Add Learning Outcome', add_lo_description: 'Add measurable learning outcomes for the program', constraints: 'Constraints',
        num_semesters: 'Number of Semesters', total_credits: 'Total Credits', max_credits_semester: 'Credits per Semester',
        min_domain_percent: 'Minimum Domain Share, %', allow_new_courses: 'Allow New Courses', max_new_courses: 'Maximum New Courses', review_data: 'Review Data',
        plan_builder: 'Curriculum Plan Builder', generate_variants: 'Build Variants', variant: 'Variant', semester: 'Semester',
        semester_lo: 'Learning Outcomes per Semester', evidence_courses: 'Evidence courses', connection_strength: 'Connection strength', programme_outcome: 'Programme outcome', course_outcome: 'Course outcome', no_semester_lo_evidence: 'This semester has no confirmed links to programme outcomes yet.', activate: 'Make Active', deactivate: 'Active Plan', mandatory: 'mandatory component',
        activate_plan_hint: 'Selecting this variant publishes the project and changes its status from Draft to Active.',
        activate_invalid_plan_hint: 'This variant cannot be activated: fix hard plan violations first.',
        activate_plan_with_warnings_hint: 'You can select this variant as active, but quality checks still show hard warnings.',
        active_plan_hint: 'This variant is approved and used as the active curriculum plan.',
        activation_success: 'Done: the variant is selected and the project is now Active.',
        university: 'university component', elective: 'elective component', variant_a_desc: '(maximum LO coverage)',
        variant_b_desc: '(minimum new courses)', variant_c_desc: '(balanced, low redundancy)', analytics: 'Analytics',
        check_coverage: 'LO Coverage Analysis', check_coverage_description: 'Analyze LO coverage by repository courses', coverage_percent: 'Coverage',
        covered: 'Covered', not_covered: 'Not Covered', verification: 'Plan Verification', feasible: 'Feasible Plan', yes: 'Yes', no: 'No', minimum: 'Minimum',
        prerequisite_violations: 'Prerequisite Violations', load_violations: 'Load Violations', min_lo_coverage: 'Minimum LO Coverage',
        evidence_count: 'Evidence Count', redundancy: 'Redundancy', 'Changes saved': 'Changes saved', 'Error saving': 'Could not save',
        'Error saving weights': 'Could not save priorities', 'Course deleted': 'Course deleted', 'Error deleting': 'Could not delete',
        'Import successful!': 'Import completed', 'Bridge module ID not found. Please regenerate.': 'Bridge module ID not found. Please regenerate.',
        knowledge_graph: 'Curriculum-KAG Knowledge Graph', build_graph: 'Build Graph', rebuild_graph: 'Rebuild Graph',
        graph_description: 'The graph connects courses, prerequisites, and learning outcomes and improves candidate retrieval.',
        embedding_mode: 'Embedding mode', mixed_index: 'Mixed index detected', reindex_all: 'Reindex All', reindexing: 'Reindexing...',
        courses_label: 'Courses', total_edges: 'Total Edges', prerequisite_links: 'Prerequisite Links', similarity_links: 'Semantic Links',
        lo_coverage_links: 'LO Coverage Links', graph_built: 'Graph Built', graph_not_built: 'The graph has not been built yet. Build it before analysis and plan generation.',
        bridge_suggestions: 'Bridge Module Suggestions', generate_bridge: 'Generate Bridge Modules', generating: 'Generating...',
        bridge_description: 'When existing courses are insufficient, the system proposes an interdisciplinary module to close the gap.',
        no_gaps: 'No gaps detected: all learning outcomes are covered.', topics: 'Topics', assessment: 'Assessment',
        promoted: 'Added to Repository', promote_course: 'Approve and Add Course', promote_desc: 'After approval, the module becomes available to new plan variants.',
        lo_achievability: 'Learning Outcome Achievability', analyze_ai: 'Analyze with AI', analyzing: 'Analyzing...',
        achievability_description: 'AI checks whether each LO is realistic with the current course set and proposes next actions.',
        achievability_score: 'Achievability Score', per_lo_recommendations: 'Recommendations by LO', all_los_good: 'All LOs are clear and covered.',
        what_next: 'What should I do next?', clarify_vague_los: 'Clarify LOs marked as too vague.', generate_missing_los: 'Generate bridge modules for uncovered LOs.',
        review_promote: 'Review the modules and approve only suitable ones.', regenerate_variants_hint: 'Build variants again; the existing plan is not changed automatically.',
        generate_missing_modules: '1. Generate Missing Modules', edit_los: 'Edit Learning Outcomes', open_plan_builder: '3. Open Plan Builder',
        save_priorities: 'Save Priorities', priorities_saved: 'Priorities saved. Now build the variants again.', international_quality: 'International Quality Checklist',
        optimizer: 'Construction method', optimizer_parameters: 'population {population}, generations {generations}',
        apply_all_quality_improvements: 'Apply all improvements', applying_quality_improvements: 'Applying improvements and rebuilding plans...',
        quality_improvements_applied: 'All available improvements were applied. Variants A/B/C were rebuilt.', quality_improvements_error: 'Could not apply improvements',
        recommendation: 'Recommendation', bridge_label: 'Bridge Module', build_error: 'Could not build the plan', activate_error: 'Could not select the plan',
        Ready: 'Ready', 'Needs Improvement': 'Needs Improvement', 'Critical Gaps': 'Critical Gaps',
        'on track': 'on track', 'needs courses': 'needs courses', 'too vague': 'too vague', critical: 'critical',
        graph_rebuilt_title: 'Knowledge Graph Updated', graph_rebuilt_text: 'The graph updated retrieval and analysis data. Existing plans were not changed; rebuild variants when needed.',
        bridge_generated_title: 'Bridge Modules Generated', bridge_generated_text: 'These are proposals; the plan has not changed. Review modules, approve suitable ones, and build variants again.',
        kb_updated_title: 'Knowledge Base Updated', kb_updated_text: 'The module was added to the repository. Build variants again to use it in a plan.',
        analysis_completed_title: 'LO Analysis Completed', analysis_completed_text: 'This is a diagnostic report. It does not change the plan automatically; follow the actions below.',
        promotion_error: 'Could not add the bridge module', open_regenerate: 'Open Plan Builder / Rebuild', hide: 'Hide', plan_label: 'Plan',
        min_lo_label: 'min LO', uncovered_los: 'Uncovered LOs (Gaps)', page_effect: 'How this page affects the curriculum plan',
        graph_effect: 'Rebuilding the graph updates retrieval but does not rewrite an existing plan.',
        bridge_effect: 'Generating bridge modules creates proposals for weak LOs; they are not courses yet.',
        promote_effect: 'Approval adds a bridge module to the repository and updates the knowledge base.',
        regenerate_effect: 'Build variants again for a new course to appear in the plan.',
        'Outcome-based curriculum mapping': 'Outcome-based curriculum mapping',
        'Structured progression and prerequisite integrity': 'Structured progression and prerequisite integrity',
        'Domain relevance control': 'Domain relevance control',
        'Integrated interdisciplinary curriculum': 'Integrated interdisciplinary curriculum',
        'Assessment alignment': 'Assessment alignment',
        'Continuous improvement and expert-in-the-loop learning': 'Continuous improvement and expert-in-the-loop learning',
        'Ensure every programme LO has explicit course or bridge-module evidence.': 'Ensure every programme LO has explicit course or bridge-module evidence.',
        'Fix prerequisite order, semester load, or total-credit violations.': 'Fix prerequisite order, semester load, or total-credit violations.',
        'Remove unrelated courses or replace them with domain-specific/bridge modules.': 'Remove unrelated courses or replace them with domain-specific/bridge modules.',
        'Review only the unsupported professional courses; RK mandatory components, practices, and final attestation are not removed in KZ mode.': 'Review only the unsupported professional courses; RK mandatory components, practices, and final attestation are not removed in KZ mode.',
        'Add bridge modules that connect the two programme domains.': 'Add bridge modules that connect the two programme domains.',
        'Add assessment methods for courses/modules to support outcome-attainment evidence.': 'Add assessment methods for courses/modules to support outcome-attainment evidence.',
        'Use Promote to Course and regenerate variants to document the learning loop.': 'Use Promote to Course and regenerate variants to document the learning loop.'
    }
}

Object.assign(translations.ru, { country_standard: 'Страна и стандарт', kz_goso: 'Республика Казахстан — ГОСО', international_program: 'Международная программа', master_track: 'Направление магистратуры', master_scientific: 'Научно-педагогическая — 120 кредитов', master_professional: 'Профильная — 60 или 90 кредитов', supported_profile_volumes: 'Допустимый объём по профилю: ' })
Object.assign(translations.kk, { country_standard: 'Ел және стандарт', kz_goso: 'Қазақстан Республикасы — МЖМБС', international_program: 'Халықаралық бағдарлама', master_track: 'Магистратура бағыты', master_scientific: 'Ғылыми-педагогикалық — 120 кредит', master_professional: 'Бейіндік — 60 немесе 90 кредит', supported_profile_volumes: 'Профиль бойынша рұқсат етілген көлем: ' })
Object.assign(translations.en, { country_standard: 'Country and standard', kz_goso: 'Republic of Kazakhstan — State standard', international_program: 'International programme', master_track: 'Master track', master_scientific: 'Scientific and pedagogical — 120 credits', master_professional: 'Professional — 60 or 90 credits', supported_profile_volumes: 'Supported profile volumes: ' })
Object.assign(translations.ru, { doctorate_track: 'Направление докторантуры', doctorate_scientific: 'Научно-педагогическое', doctorate_professional: 'Профессиональное' })
Object.assign(translations.kk, { doctorate_track: 'Докторантура бағыты', doctorate_scientific: 'Ғылыми-педагогикалық', doctorate_professional: 'Кәсіби' })
Object.assign(translations.en, { doctorate_track: 'Doctorate track', doctorate_scientific: 'Scientific and pedagogical', doctorate_professional: 'Professional' })
Object.assign(translations.ru, { epvo_scope_hint: 'Направления и группы ЕПВО определяют, из каких дисциплин система будет строить программу.' })
Object.assign(translations.kk, { epvo_scope_hint: 'ЕПВО бағыттары мен топтары жүйе бағдарламаны қандай пәндерден құратынын анықтайды.' })
Object.assign(translations.en, { epvo_scope_hint: 'EPVO fields and programme groups define which courses the system may use to build the curriculum.' })
// Bridge replacement copy is kept in the same catalog, separately grouped to
// keep the large language tables readable while preserving RU/KK/EN parity.
Object.assign(translations.ru, {
    bridge_review: 'Bridge-модули требуют экспертного решения', bridge_review_desc: 'Это значит, что реальных дисциплин ЕПВО не хватило для части LO или нагрузки. Лучше перенастроить ЕПВО-направление или заменить bridge реальными дисциплинами.', find_real_courses: 'Найти реальные дисциплины вместо bridge', replace_all_bridges: 'Заменить все подходящие bridge', select_medium: 'Выбрать все средние замены', replacement_summary: 'Итог поиска замен', replacement_summary_text: '{count} bridge · {credits} кредитов · сильных: {strong} · средних: {medium} · без сильной: {without}.', replacement_search_done: 'Поиск замен выполнен за {seconds}s.', strong_quality: 'сильная', medium_quality: 'средняя, нужно подтвердить', adding: 'Добавление…', no_strong_replacement: 'Сильной замены пока нет. Автозамена требует подтверждение ЕПВО ≥ 50%, покрытие ≥ 75% профессиональных LO, близкие кредиты и область выбранного направления.', ai_generating: 'ИИ подбирает 3 варианта…', generate_ai_courses: 'Подобрать 3 дисциплины через ИИ', confirming: 'Подтверждение…', confirm_replace_bridge: 'Подтвердить и заменить bridge', ai_proposal: 'Это предложение ИИ. В план оно попадёт только после вашего подтверждения.', rebuilding: 'Перестроение…', regenerate_changes: 'Перегенерировать A/B/C с изменениями'
})
Object.assign(translations.kk, {
    bridge_review: 'Bridge-модульдер сараптамалық шешімді қажет етеді', bridge_review_desc: 'Бұл кейбір LO немесе жүктеме үшін нақты ЕПВО пәндері жеткіліксіз екенін білдіреді. ЕПВО бағытын қайта баптау немесе bridge орнына нақты пәндерді таңдау ұсынылады.', find_real_courses: 'Bridge орнына нақты пәндерді табу', replace_all_bridges: 'Барлық қолайлы bridge-модульдерді ауыстыру', select_medium: 'Барлық орташа ауыстыруларды таңдау', replacement_summary: 'Ауыстыру іздеу қорытындысы', replacement_summary_text: '{count} bridge · {credits} кредит · күшті: {strong} · орташа: {medium} · күштісіз: {without}.', replacement_search_done: 'Ауыстыруларды іздеу {seconds}s ішінде орындалды.', strong_quality: 'күшті', medium_quality: 'орташа, растау керек', adding: 'Қосу…', no_strong_replacement: 'Әзірше күшті ауыстыру жоқ. Автоауыстыру үшін ЕПВО растауы ≥ 50%, кәсіби ОН қамтуы ≥ 75%, жақын кредиттер және таңдалған бағыт қажет.', ai_generating: 'ЖИ 3 нұсқа таңдауда…', generate_ai_courses: 'ЖИ арқылы 3 пән ұсыну', confirming: 'Растау…', confirm_replace_bridge: 'Растау және bridge ауыстыру', ai_proposal: 'Бұл ЖИ ұсынысы. Жоспарға тек сіз растағаннан кейін енгізіледі.', rebuilding: 'Қайта құру…', regenerate_changes: 'Өзгерістермен A/B/C қайта құру'
})
Object.assign(translations.en, {
    bridge_review: 'Bridge modules require expert review', bridge_review_desc: 'This means real EPVO courses were insufficient for some LOs or workload. Reconfigure the EPVO scope or replace bridges with real courses.', find_real_courses: 'Find real courses instead of bridges', replace_all_bridges: 'Replace all suitable bridges', select_medium: 'Select all medium replacements', replacement_summary: 'Replacement search summary', replacement_summary_text: '{count} bridges · {credits} credits · strong: {strong} · medium: {medium} · without strong: {without}.', replacement_search_done: 'Replacement search completed in {seconds}s.', strong_quality: 'strong', medium_quality: 'medium, needs confirmation', adding: 'Adding…', no_strong_replacement: 'No strong replacement yet. Automatic replacement requires EPVO evidence ≥ 50%, coverage of ≥ 75% of professional LOs, similar credits, and the selected programme scope.', ai_generating: 'AI is generating 3 options…', generate_ai_courses: 'Generate 3 courses with AI', confirming: 'Confirming…', confirm_replace_bridge: 'Confirm and replace bridge', ai_proposal: 'This is an AI proposal. It enters the plan only after your confirmation.', rebuilding: 'Rebuilding…', regenerate_changes: 'Regenerate A/B/C with changes'
})

Object.assign(translations.ru, { ceer_passed: 'Соответствует ориентиру CEER 75%+', ceer_borderline: 'Близко к ориентиру CEER; нужна экспертная проверка', ceer_below: 'Ниже ориентира CEER 70–75%', ceer_expert_evidence: '{support}: {supported}/{total} связей с LO поддержаны исторической экспертной разметкой CEER.', similar_programs_title: 'Сравнение с аналогичными программами экспертной базы', similar_programs_desc: 'Показаны похожие программы выбранного направления CEER, их типовые дисциплины и результаты обучения.' })
Object.assign(translations.kk, { ceer_passed: 'CEER 75%+ бағдарына сәйкес', ceer_borderline: 'CEER бағдарына жақын; сараптамалық тексеру қажет', ceer_below: 'CEER 70–75% бағдарынан төмен', ceer_expert_evidence: '{support}: {supported}/{total} LO байланысы CEER тарихи сараптамалық бағаларымен расталған.', similar_programs_title: 'Сараптамалық базадағы ұқсас бағдарламалармен салыстыру', similar_programs_desc: 'Таңдалған CEER бағыты бойынша ұқсас бағдарламалар, типтік пәндер және оқу нәтижелері көрсетіледі.' })
Object.assign(translations.en, { ceer_passed: 'Meets the CEER 75%+ reference level', ceer_borderline: 'Close to the CEER reference level; expert review is required', ceer_below: 'Below the CEER 70–75% reference level', ceer_expert_evidence: '{support}: {supported}/{total} LO links are supported by historical CEER expert evidence.', similar_programs_title: 'Compare with similar expert-repository programmes', similar_programs_desc: 'This section shows similar programmes from the selected CEER scope, their typical courses and learning outcomes.' })
Object.assign(translations.ru, { load_program_error: 'Не удалось загрузить данные программы', load_analytics_error: 'Не удалось загрузить анализ', refreshing_coverage: 'Обновляю покрытие и источники LO…', coverage_sources_done: 'Источники покрытия рассчитаны за {seconds}s.' })
Object.assign(translations.kk, { load_program_error: 'Бағдарлама деректерін жүктеу мүмкін болмады', load_analytics_error: 'Талдауды жүктеу мүмкін болмады', refreshing_coverage: 'LO қамтуы мен көздерін жаңартып жатырмын…', coverage_sources_done: 'Қамту көздері {seconds}s ішінде есептелді.' })
Object.assign(translations.en, { load_program_error: 'Could not load programme data', load_analytics_error: 'Could not load analytics', refreshing_coverage: 'Refreshing LO coverage and sources…', coverage_sources_done: 'Coverage sources calculated in {seconds}s.' })
Object.assign(translations.ru, { unknown_error: 'Неизвестная ошибка', open_collapse: 'Открыть / свернуть', recompute_success: 'Связи дисциплина–LO пересчитаны: {count}. Теперь можно перестроить варианты.', recompute_error: 'Не удалось пересчитать связи', bridge_preview_error: 'Не удалось получить preview замены bridge', course_added: 'Дисциплина добавлена в план.', bridge_replace_error: 'Не удалось заменить bridge-модуль', bridge_replace_all_error: 'Не удалось массово заменить bridge-модули', ai_courses_error: 'Не удалось подобрать дисциплины через ИИ', course_confirm_error: 'Не удалось подтвердить дисциплину', exclusion_error: 'Не удалось изменить исключение дисциплины', replacements_error: 'Не удалось подобрать замены', replacement_confirm_error: 'Не удалось подтвердить замену', coverage_sources_error: 'Не удалось получить источники покрытия LO', feedback_save_error: 'Не удалось сохранить экспертную оценку' })
Object.assign(translations.kk, { unknown_error: 'Белгісіз қате', open_collapse: 'Ашу / жинау', recompute_success: 'Пән–LO байланыстары қайта есептелді: {count}. Енді нұсқаларды қайта құруға болады.', recompute_error: 'Байланыстарды қайта есептеу мүмкін болмады', bridge_preview_error: 'Bridge ауыстыру preview алу мүмкін болмады', course_added: 'Пән жоспарға қосылды.', bridge_replace_error: 'Bridge-модульді ауыстыру мүмкін болмады', bridge_replace_all_error: 'Bridge-модульдерді жаппай ауыстыру мүмкін болмады', ai_courses_error: 'ЖИ арқылы пәндерді таңдау мүмкін болмады', course_confirm_error: 'Пәнді растау мүмкін болмады', exclusion_error: 'Пәнді алып тастау белгісін өзгерту мүмкін болмады', replacements_error: 'Ауыстыруларды таңдау мүмкін болмады', replacement_confirm_error: 'Ауыстыруды растау мүмкін болмады', coverage_sources_error: 'LO қамту көздерін алу мүмкін болмады', feedback_save_error: 'Сарапшы бағасын сақтау мүмкін болмады' })
Object.assign(translations.en, { unknown_error: 'Unknown error', open_collapse: 'Open / collapse', recompute_success: 'Course–LO links recomputed: {count}. You can now rebuild variants.', recompute_error: 'Could not recompute links', bridge_preview_error: 'Could not load bridge replacement preview', course_added: 'Course added to the plan.', bridge_replace_error: 'Could not replace bridge module', bridge_replace_all_error: 'Could not replace bridge modules', ai_courses_error: 'Could not generate AI course candidates', course_confirm_error: 'Could not confirm the course', exclusion_error: 'Could not update course exclusion', replacements_error: 'Could not find replacements', replacement_confirm_error: 'Could not confirm replacement', coverage_sources_error: 'Could not load LO coverage sources', feedback_save_error: 'Could not save expert feedback' })
Object.assign(translations.ru, { selected_medium_replacements: 'Выбрано средних замен: {count}. Проверьте список и нажмите подтверждение.', no_medium_replacements: 'Средних замен пока нет.', build_missing: 'Построить отсутствующие: ', recompute_links: 'Пересчитать LO-связи', epvo_candidates_added: 'EPVO-кандидаты добавлены', epvo_candidates_hint: 'Нажмите “Построить варианты”, чтобы A/B/C использовали новые дисциплины.', changes_next_generation: 'Есть изменения для следующей генерации', changes_next_generation_hint: 'Система учтёт замены bridge и отмеченные исключения, затем заново рассчитает A/B/C, кредиты, РО и пререквизиты.', regenerate_abc: 'Перегенерировать A/B/C' })
Object.assign(translations.kk, { selected_medium_replacements: 'Орташа ауыстырулар таңдалды: {count}. Тізімді тексеріп, растаңыз.', no_medium_replacements: 'Орташа ауыстырулар жоқ.', build_missing: 'Жетпейтін нұсқаларды құру: ', recompute_links: 'LO байланыстарын қайта есептеу', epvo_candidates_added: 'ЕПВО кандидаттары қосылды', epvo_candidates_hint: 'Жаңа пәндер A/B/C нұсқаларында қолданылуы үшін “Нұсқаларды құру” түймесін басыңыз.', changes_next_generation: 'Келесі құру үшін өзгерістер бар', changes_next_generation_hint: 'Жүйе bridge ауыстыруларын және белгіленген алып тастауларды ескеріп, A/B/C, кредиттер, ОН және пререквизиттерді қайта есептейді.', regenerate_abc: 'A/B/C қайта құру' })
Object.assign(translations.en, { selected_medium_replacements: 'Selected medium replacements: {count}. Review and confirm.', no_medium_replacements: 'No medium replacements available.', build_missing: 'Build missing: ', recompute_links: 'Recompute LO links', epvo_candidates_added: 'EPVO candidates added', epvo_candidates_hint: 'Click “Build variants” so A/B/C can use the new courses.', changes_next_generation: 'Changes are ready for the next generation', changes_next_generation_hint: 'The system will apply bridge replacements and exclusions, then recalculate A/B/C, credits, LOs, and prerequisites.', regenerate_abc: 'Regenerate A/B/C' })
Object.assign(translations.ru, { replacements_loaded: 'Подобраны замены для', replacements_visible_error: 'Не удалось подобрать замены для видимых дисциплин' })
Object.assign(translations.kk, { replacements_loaded: 'Ауыстырулар таңдалды:', replacements_visible_error: 'Көрінетін пәндер үшін ауыстыру табылмады' })
Object.assign(translations.en, { replacements_loaded: 'Loaded replacements for', replacements_visible_error: 'Could not load replacements for visible courses' })
Object.assign(translations.ru, { build_result_error: 'Построение завершено без публикации результата' })
Object.assign(translations.kk, { build_result_error: 'Құру нәтижесі жарияланбай аяқталды' })
Object.assign(translations.en, { build_result_error: 'Build finished without publishing a result' })
Object.assign(translations.ru, { retry_build: 'Повторить построение' })
Object.assign(translations.kk, { retry_build: 'Құруды қайталау' })
Object.assign(translations.en, { retry_build: 'Retry build' })
Object.assign(translations.ru, { changes_after_rebuild: 'Что изменилось после перестройки', bridge_modules_label: 'Bridge-модули', minimum_lo: 'Минимальное покрытие РО', quality_label: 'Качество', added_label: 'Добавлено', removed_label: 'удалено', show_change_examples: 'Показать примеры изменений', duplicate_variants: 'Внимание: варианты совпадают', duplicate_variants_desc: 'Сохранённые варианты {variants} имеют одинаковый состав дисциплин. Это не разные альтернативы. Перестройте только эти варианты после изменения ограничений или состава ЕПВО.' })
Object.assign(translations.kk, { changes_after_rebuild: 'Қайта құрудан кейін не өзгерді', bridge_modules_label: 'Bridge-модульдер', minimum_lo: 'ОН ең төменгі қамтылуы', quality_label: 'Сапа', added_label: 'Қосылды', removed_label: 'жойылды', show_change_examples: 'Өзгерістер мысалдарын көрсету', duplicate_variants: 'Назар аударыңыз: нұсқалар бірдей', duplicate_variants_desc: 'Сақталған {variants} нұсқаларының пәндер құрамы бірдей. Бұл әртүрлі балама емес. Шектеулерді немесе ЕПВО құрамын өзгерткеннен кейін осы нұсқаларды қайта құрыңыз.' })
Object.assign(translations.en, { changes_after_rebuild: 'What changed after rebuild', bridge_modules_label: 'Bridge modules', minimum_lo: 'Minimum LO coverage', quality_label: 'Quality', added_label: 'Added', removed_label: 'Removed', show_change_examples: 'Show change examples', duplicate_variants: 'Warning: variants are identical', duplicate_variants_desc: 'Saved variants {variants} have the same course composition. They are not distinct alternatives. Rebuild these variants after changing the EPVO scope or constraints.' })
Object.assign(translations.ru, { show_course_descriptions: 'Показывать описания дисциплин', show_selection_reasons: 'Показывать подробные обоснования выбора', quality_passed_notice: 'План уже прошёл международный чек-лист.', quality_repair_notice: 'План требует автоматического исправления.', quality_notice_desc: 'Система проверяет кредиты, нагрузку по семестрам, пререквизиты, покрытие результатов обучения, предметную релевантность и защиту обязательных ГОСО-компонентов. Кнопка ниже исключает только заменяемые слабые дисциплины, защищает ГОСО и запускает пересборку A/B/C, если это действительно нужно.', what_system_checks: 'Что проверяет система', relevant_courses: 'Релевантные дисциплины', protected_goso: 'Из них защищены как ГОСО РК', safely_replaceable: 'Можно заменить без риска', goso_not_removed: 'ГОСО не удаляется', replacement_candidates: 'Кандидаты на замену' })
Object.assign(translations.kk, { show_course_descriptions: 'Пән сипаттамаларын көрсету', show_selection_reasons: 'Таңдаудың толық негіздемесін көрсету', quality_passed_notice: 'Жоспар халықаралық чек-листен өтті.', quality_repair_notice: 'Жоспар автоматты түзетуді қажет етеді.', quality_notice_desc: 'Жүйе кредиттерді, семестр жүктемесін, пререквизиттерді, оқу нәтижелерін қамтуды, пәндік сәйкестікті және міндетті МЖМБС компоненттерін қорғауды тексереді. Төмендегі батырма тек ауыстыруға болатын әлсіз пәндерді алып тастайды, МЖМБС-ты қорғайды және қажет болса A/B/C қайта құрады.', what_system_checks: 'Жүйе нені тексереді', relevant_courses: 'Сәйкес пәндер', protected_goso: 'Оның ішінде ҚР МЖМБС ретінде қорғалған', safely_replaceable: 'Қауіпсіз ауыстыруға болады', goso_not_removed: 'МЖМБС жойылмайды', replacement_candidates: 'Ауыстыруға үміткерлер' })
Object.assign(translations.en, { show_course_descriptions: 'Show course descriptions', show_selection_reasons: 'Show detailed selection reasons', quality_passed_notice: 'The plan already passed the international checklist.', quality_repair_notice: 'The plan needs automatic repair.', quality_notice_desc: 'The system checks credits, semester load, prerequisites, LO coverage, domain relevance, and protected regulatory components. The button excludes only replaceable weak courses, protects RK mandatory courses, and rebuilds A/B/C only when needed.', what_system_checks: 'What the system checks', relevant_courses: 'Relevant courses', protected_goso: 'Protected as RK regulatory', safely_replaceable: 'Safely replaceable', goso_not_removed: 'Regulatory courses are not removed', replacement_candidates: 'Replacement candidates' })
Object.assign(translations.ru, { versions: 'Версии', courses: 'Дисциплины', suggest_courses_ai: 'Предложить дисциплины с ИИ', subject_area: 'Предметная область', subject_placeholder: 'Например: информационная безопасность, анализ данных, медицина', course_count: 'Количество дисциплин', generate: 'Создать', generated_courses: '✅ Создано дисциплин: {count}. Таблица обновлена.', translation_needed: 'Нужен перевод KK/EN', title_ru: 'Название — русский', title_kk: 'Название — казахский', title_en: 'Название — английский', description_ru: 'Описание дисциплины — русский', description_kk: 'Описание дисциплины — казахский', description_en: 'Описание дисциплины — английский', description_missing_ru: 'Описание пока отсутствует', description_missing_kk: 'Казахское описание пока отсутствует', description_missing_en: 'Английское описание пока отсутствует', description_placeholder_ru: 'Введите описание на русском', description_placeholder_kk: 'Введите описание на казахском', description_placeholder_en: 'Введите описание на английском', edit_translations: 'Редактировать описания RU/KK/EN' })
Object.assign(translations.kk, { versions: 'Нұсқалар', courses: 'Пәндер', suggest_courses_ai: 'ЖИ арқылы пәндерді ұсыну', subject_area: 'Пәндік сала', subject_placeholder: 'Мысалы: ақпараттық қауіпсіздік, деректер ғылымы, медицина', course_count: 'Пәндер саны', generate: 'Құру', generated_courses: '✅ Құрылған пәндер: {count}. Кесте жаңартылды.', translation_needed: 'KK/EN аудармасы қажет', title_ru: 'Атауы — орысша', title_kk: 'Атауы — қазақша', title_en: 'Атауы — ағылшынша', description_ru: 'Пән сипаттамасы — орысша', description_kk: 'Пән сипаттамасы — қазақша', description_en: 'Пән сипаттамасы — ағылшынша', description_missing_ru: 'Сипаттама әзірге жоқ', description_missing_kk: 'Қазақша сипаттама әзірге жоқ', description_missing_en: 'Ағылшынша сипаттама әзірге жоқ', description_placeholder_ru: 'Орыс тіліндегі сипаттаманы енгізіңіз', description_placeholder_kk: 'Қазақ тіліндегі сипаттаманы енгізіңіз', description_placeholder_en: 'Ағылшын тіліндегі сипаттаманы енгізіңіз', edit_translations: 'RU/KK/EN сипаттамаларын өңдеу' })
Object.assign(translations.en, { versions: 'Versions', courses: 'Courses', suggest_courses_ai: 'Suggest courses with AI', subject_area: 'Subject area', subject_placeholder: 'e.g. information security, data science, medicine', course_count: 'Number of courses', generate: 'Generate', generated_courses: '✅ Generated courses: {count}. Table refreshed.', translation_needed: 'KK/EN translation needed', title_ru: 'Title — Russian', title_kk: 'Title — Kazakh', title_en: 'Title — English', description_ru: 'Course description — Russian', description_kk: 'Course description — Kazakh', description_en: 'Course description — English', description_missing_ru: 'Description is not available yet', description_missing_kk: 'Kazakh description is not available yet', description_missing_en: 'English description is not available yet', description_placeholder_ru: 'Enter the Russian description', description_placeholder_kk: 'Enter the Kazakh description', description_placeholder_en: 'Enter the English description', edit_translations: 'Edit RU/KK/EN descriptions' })
Object.assign(translations.ru, { ai_analyzing_semester: 'ИИ анализирует…', explain_semester_ai: '✨ Объяснить итог семестра через ИИ', ai_generated_from_evidence: 'Сформировано ИИ по дисциплинам и РО', local_evidence_explanation: 'Локальное объяснение по подтверждённым РО' })
Object.assign(translations.kk, { ai_analyzing_semester: 'ЖИ талдап жатыр…', explain_semester_ai: '✨ Семестр нәтижесін ЖИ арқылы түсіндіру', ai_generated_from_evidence: 'Пәндер мен ОН дәлелдері бойынша ЖИ қалыптастырды', local_evidence_explanation: 'Расталған ОН бойынша жергілікті түсіндірме' })
Object.assign(translations.en, { ai_analyzing_semester: 'AI is analysing…', explain_semester_ai: '✨ Explain semester outcome with AI', ai_generated_from_evidence: 'Generated by AI from course/LO evidence', local_evidence_explanation: 'Local evidence-based explanation' })
Object.assign(translations.ru, { build: 'Строить' })
Object.assign(translations.kk, { build: 'Құру' })
Object.assign(translations.en, { build: 'Build' })
Object.assign(translations.ru, { dashboard_subtitle: 'Проектируйте образовательные программы, проверяйте результаты обучения и управляйте учебными планами в одном спокойном рабочем пространстве.' })
Object.assign(translations.kk, { dashboard_subtitle: 'Білім беру бағдарламаларын жобалаңыз, оқу нәтижелерін тексеріңіз және оқу жоспарларын бір жұмыс кеңістігінде басқарыңыз.' })
Object.assign(translations.en, { dashboard_subtitle: 'Design programmes, verify learning outcomes and manage curricula in one focused workspace.' })
Object.assign(translations.ru, { optional_enrichment_label: 'Создать дополнительный модуль', optional_enrichment_helper: 'Непокрытых LO нет, поэтому система создаст дополнительный bridge-модуль для усиления программы.', coverage_strength_title: 'Какие РО нужно усилить', coverage_strength_desc: 'Сравнивайте A/B/C: полоса показывает силу покрытия, а ниже — реальные дисциплины и bridge-источники.', ai_prediction_label: 'Прогноз ИИ', ai_prediction_title: 'Связи дисциплин и результатов обучения предложены моделью ЕПВО', ai_prediction_disclaimer: 'Это рекомендация, а не решение эксперта. Перед утверждением программы подтвердите или исправьте связи.', graph_plain_title: 'Для чего это нужно простыми словами', graph_plain_desc: 'Граф связывает дисциплины, пререквизиты и РО. После нажатия система заново пересчитает связи для поиска, объяснений и рекомендаций; существующий учебный план не изменится автоматически.' })
Object.assign(translations.kk, { optional_enrichment_label: 'Қосымша тереңдетілген модуль құру', optional_enrichment_helper: 'Ашық LO жоқ, сондықтан жүйе бағдарламаны күшейту үшін қосымша bridge-модуль ұсынады.', coverage_strength_title: 'Қай ОН күшейту керек', coverage_strength_desc: 'A/B/C салыстырыңыз: жолақ қамту күшін, төменде нақты пәндер мен bridge көздерін көрсетеді.', ai_prediction_label: 'ЖИ болжамы', ai_prediction_title: 'Пәндер мен оқу нәтижелерінің байланыстарын ЕПВО моделі ұсынды', ai_prediction_disclaimer: 'Бұл сарапшы шешімі емес, ұсыныс. Бағдарламаны бекітпес бұрын байланыстарды растаңыз немесе түзетіңіз.', graph_plain_title: 'Қарапайым тілмен не үшін керек', graph_plain_desc: 'Граф пәндерді, пререквизиттерді және ОН байланыстырады. Батырмадан кейін жүйе іздеу, түсіндіру және ұсыныстар үшін байланыстарды қайта есептейді; оқу жоспары автоматты түрде өзгермейді.' })
Object.assign(translations.en, { optional_enrichment_label: 'Create optional enrichment module', optional_enrichment_helper: 'There are no uncovered LOs, so the system will create an optional enrichment bridge module rather than a required gap fix.', coverage_strength_title: 'Which outcomes need strengthening', coverage_strength_desc: 'Compare A/B/C: bars show coverage strength; real courses and bridge sources are listed below.', ai_prediction_label: 'AI prediction', ai_prediction_title: 'Course–outcome links are suggested by the EPVO model', ai_prediction_disclaimer: 'This is a recommendation, not an expert decision. Confirm or correct the links before approval.', graph_plain_title: 'What this does, in plain language', graph_plain_desc: 'The graph connects courses, prerequisites, and outcomes. Clicking rebuild recalculates links for search, explanations, and recommendations; it does not automatically change the curriculum.' })
Object.assign(translations.ru, { learning_outcomes_analysis: 'Анализ результатов обучения', covered_by_real_courses: 'закрыто реальными дисциплинами', bridge_only_strengthen: 'только bridge — лучше усилить', needs_strengthening: 'нужно усилить', read_score: 'Как читать процент', no_confirmed_real_course: 'Нет подтверждённой реальной дисциплины — эту РО нужно усилить.', lo_action_hint: 'Что делать: добавить/заменить дисциплину из ЕПВО с сильной связью к этой РО или подтвердить связь экспертом.', priority: 'Приоритет' })
Object.assign(translations.kk, { learning_outcomes_analysis: 'Оқу нәтижелерін талдау', covered_by_real_courses: 'нақты пәндермен жабылған', bridge_only_strengthen: 'тек bridge — күшейту керек', needs_strengthening: 'күшейту керек', read_score: 'Пайызды қалай оқу керек', no_confirmed_real_course: 'Расталған нақты пән жоқ — осы ОН күшейту керек.', lo_action_hint: 'Не істеу керек: осы ОН-ға күшті байланысы бар ЕПВО пәнін қосу/ауыстыру немесе байланысты сарапшымен растау.', priority: 'Басымдық' })
Object.assign(translations.en, { learning_outcomes_analysis: 'Learning outcomes analysis', covered_by_real_courses: 'covered by real courses', bridge_only_strengthen: 'bridge only — strengthen', needs_strengthening: 'needs strengthening', read_score: 'How to read the score', no_confirmed_real_course: 'No confirmed real course — strengthen this outcome.', lo_action_hint: 'Action: add/replace with an EPVO course strongly linked to this LO, or confirm the link by expert review.', priority: 'Priority' })
Object.assign(translations.ru, { epvo_expert_label: 'ЕПВО эксперт', expert_label: 'эксперт', epvo_setup_saved: 'ЕПВО-настройка сохранена. Теперь можно перестроить план.', save_epvo_setup: 'Сохранить ЕПВО-настройку', rebuild_plan: 'Перестроить план' })
Object.assign(translations.kk, { epvo_expert_label: 'ЕПВО сарапшысы', expert_label: 'сарапшы', epvo_setup_saved: 'ЕПВО баптауы сақталды. Енді жоспарды қайта құруға болады.', save_epvo_setup: 'ЕПВО баптауын сақтау', rebuild_plan: 'Жоспарды қайта құру' })
Object.assign(translations.en, { epvo_expert_label: 'EPVO expert', expert_label: 'expert', epvo_setup_saved: 'EPVO setup saved. You can now rebuild the plan.', save_epvo_setup: 'Save EPVO setup', rebuild_plan: 'Rebuild plan' })
Object.assign(translations.ru, {
    repository_scope_hint: 'Если в выбранном направлении нет дисциплин, добавьте нормализованные записи ЕПВО в утверждённый репозиторий.', repository_indexing: 'Индексация ЕПВО…', repository_index: 'Индексировать ЕПВО', prerequisite_exempt: 'Для этой базовой дисциплины пререквизиты не требуются',
    goso_components_protected: 'ГОСО-компонентов защищены; пересборка не требуется.', rebuild_not_required: 'Пересборка не требуется.', bridge_enrichment_title: 'Дополнительный модуль создан', bridge_enrichment_text: 'Это необязательный модуль углубления. Добавляйте его в репозиторий только после экспертной проверки.'
})
Object.assign(translations.kk, {
    repository_scope_hint: 'Таңдалған бағытта пәндер болмаса, нормаланған ЕПВО жазбаларын бекітілген репозиторийге қосыңыз.', repository_indexing: 'ЕПВО индекстелуде…', repository_index: 'ЕПВО-ны индекстеу', prerequisite_exempt: 'Бұл базалық пән үшін пререквизиттер қажет емес',
    goso_components_protected: 'ГОСО компоненті қорғалды; қайта құру қажет емес.', rebuild_not_required: 'Қайта құру қажет емес.', bridge_enrichment_title: 'Қосымша модуль жасалды', bridge_enrichment_text: 'Бұл міндетті емес тереңдету модулі. Репозиторийге тек сарапшы тексергеннен кейін қосыңыз.'
})
Object.assign(translations.en, {
    repository_scope_hint: 'If the selected direction has no courses, add normalized EPVO records to the approved repository.', repository_indexing: 'Indexing EPVO…', repository_index: 'Index EPVO', prerequisite_exempt: 'Prerequisites are not required for this basic course',
    goso_components_protected: 'GOSO components protected; rebuild is not required.', rebuild_not_required: 'Rebuild is not required.', bridge_enrichment_title: 'Additional module created', bridge_enrichment_text: 'This is an optional enrichment module. Add it to the repository only after expert review.'
})
Object.assign(translations.ru, { epvo_setup_incomplete: 'Настройка ЕПВО неполная', epvo_setup_warning: 'Программа создана без корректного направления или группы ЕПВО. Генератор может подобрать лишние дисциплины и bridge-модули.', current_epvo_values: 'Текущие значения: область {area}, направление {direction}, группа {group}', education_area_option: 'Область образования', direction_option: 'Направление подготовки', group_option: 'Группа образовательных программ' })
Object.assign(translations.kk, { epvo_setup_incomplete: 'ЕПВО баптауы толық емес', epvo_setup_warning: 'Бағдарлама дұрыс ЕПВО бағыты немесе тобы көрсетілмей жасалған. Генератор артық пәндер мен bridge-модульдерді таңдауы мүмкін.', current_epvo_values: 'Ағымдағы мәндер: сала {area}, бағыт {direction}, топ {group}', education_area_option: 'Білім беру саласы', direction_option: 'Дайындық бағыты', group_option: 'Білім беру бағдарламаларының тобы' })
Object.assign(translations.en, { epvo_setup_incomplete: 'EPVO setup is incomplete', epvo_setup_warning: 'This programme was created without a valid EPVO direction or group. The generator may select unrelated courses and bridge modules.', current_epvo_values: 'Current values: area {area}, direction {direction}, group {group}', education_area_option: 'Education area', direction_option: 'Study direction', group_option: 'Programme group' })
Object.assign(translations.ru, { dashboard_overview: 'Обзор рабочего пространства', dashboard_load_error: 'Не удалось загрузить данные панели', dashboard_load_error_hint: 'Проверьте соединение с сервером и повторите попытку.', retry: 'Повторить' })
Object.assign(translations.kk, { dashboard_overview: 'Жұмыс кеңістігіне шолу', dashboard_load_error: 'Бақылау тақтасының деректерін жүктеу мүмкін болмады', dashboard_load_error_hint: 'Сервер байланысын тексеріп, қайталап көріңіз.', retry: 'Қайталау' })
Object.assign(translations.en, { dashboard_overview: 'Workspace overview', dashboard_load_error: 'Dashboard data could not be loaded', dashboard_load_error_hint: 'Check the server connection and try again.', retry: 'Retry' })
